CCTV_COMMANDS = {
    "🌐 RTSP / Streaming": [
        ("rtsp://CAMERA_IP:554/Streaming/Channels/101", "Stream principal Hikvision (sub+main)"),
        ("rtsp://CAMERA_IP:554/Streaming/Channels/102", "Stream secundario Hikvision"),
        ("rtsp://CAMERA_IP:554/user=admin&password=12345&channel=1&stream=0.sdp", "Stream principal Dahua"),
        ("rtsp://CAMERA_IP:554/user=admin&password=12345&channel=1&stream=1.sdp", "Stream secundario Dahua"),
        ("rtsp://CAMERA_IP:554/live/ch00_0", "Stream principal Hikvision NVR"),
        ("rtsp://CAMERA_IP:554/live/ch01_0", "Stream cámara 1 desde NVR"),
        ("rtsp://CAMERA_IP:554/onvif1", "Stream ONVIF perfil S"),
        ("rtsp://CAMERA_IP:554/h264_stream", "Stream H264 genérico"),
        ("rtsp://CAMERA_IP:554/mpeg4_stream", "Stream MPEG4 genérico"),
        ("rtsp://CAMERA_IP:554/unicast", "Stream unicast"),
        ("rtsp://CAMERA_IP/axis-media/media.amp", "Stream Axis Communications"),
        ("rtsp://CAMERA_IP:554/play1.sdp", "Stream Bosch"),
        ("ffplay rtsp://CAMERA_IP:554/...", "Probar stream con ffplay"),
        ("ffmpeg -i rtsp://... -vframes 1 out.jpg", "Capturar frame desde RTSP"),
    ],
    "📸 HTTP Snapshots": [
        ("http://CAMERA_IP/snapshot.cgi?user=admin&pwd=12345", "Snapshot Dahua"),
        ("http://CAMERA_IP/cgi-bin/snapshot.cgi?channel=1", "Snapshot Dahua CGI"),
        ("http://CAMERA_IP/ISAPI/Streaming/channels/101/picture", "Snapshot Hikvision ISAPI"),
        ("http://CAMERA_IP/Streaming/Channels/1/picture", "Snapshot Hikvision antigua"),
        ("http://CAMERA_IP/axis-cgi/jpg/image.cgi", "Snapshot Axis"),
        ("http://CAMERA_IP/cgi-bin/video.jpg", "Snapshot Bosch"),
        ("http://CAMERA_IP/snap.jpg", "Snapshot genérico"),
        ("http://CAMERA_IP/capture", "Snapshot Vivotek"),
        ("http://CAMERA_IP/img/snapshot.cgi", "Snapshot Uniview"),
    ],
    "📡 ONVIF": [
        ("wsdl://CAMERA_IP/onvif/device_service", "Servicio de dispositivo ONVIF"),
        ("wsdl://CAMERA_IP/onvif/media_service", "Servicio de media ONVIF"),
        ("wsdl://CAMERA_IP/onvif/ptz_service", "Servicio PTZ ONVIF"),
        ("wsdl://CAMERA_IP/onvif/events_service", "Servicio de eventos ONVIF"),
        ("wsdl://CAMERA_IP/onvif/analytics_service", "Servicio de analíticos ONVIF"),
        ("wsdl://CAMERA_IP/onvif/recording_service", "Servicio de grabación ONVIF"),
        ("onvif://admin:12345@CAMERA_IP", "URL de descubrimiento ONVIF"),
        ("WS-Discovery multicast", "Descubrir dispositivos ONVIF en red (puerto 3702)"),
        ("Probe: tipo NetworkVideoTransmitter", "Buscar solo cámaras ONVIF"),
        ("Port 80: /onvif/device_service", "ONVIF sobre HTTP (común)"),
        ("Port 8080: /onvif/device_service", "ONVIF sobre HTTP alternativo"),
    ],
    "🔄 Hikvision ISAPI": [
        ("GET /ISAPI/System/deviceInfo", "Info del dispositivo (modelo, serial, firmware, MAC)"),
        ("GET /ISAPI/System/status", "Estado general del dispositivo"),
        ("GET /ISAPI/System/Network/interfaces/1", "Configuración de red (IP, máscara, gateway)"),
        ("GET /ISAPI/System/Network/interfaces/1/dns", "Servidores DNS configurados"),
        ("GET /ISAPI/System/Storage/status", "Estado de almacenamiento (HDD, SD)"),
        ("GET /ISAPI/System/Storage/hdd/1", "Info detallada del HDD"),
        ("GET /ISAPI/System/time", "Hora y fecha del dispositivo"),
        ("PUT /ISAPI/System/time", "Configurar hora del dispositivo"),
        ("GET /ISAPI/Streaming/channels/1", "Estado del canal 1 (resolución, codec, fps)"),
        ("GET /ISAPI/Streaming/channels/101", "Canal 101 (main stream)"),
        ("GET /ISAPI/Streaming/channels/102", "Canal 102 (sub stream)"),
        ("GET /ISAPI/Streaming/channels/1/picture", "Capturar snapshot del canal 1"),
        ("GET /ISAPI/Event/triggers", "Reglas de eventos/detección activas"),
        ("GET /ISAPI/Event/notification/alertStream", "Alertas en tiempo real (eventos)"),
        ("GET /ISAPI/PTZCtrl/channels/1", "Estado de control PTZ"),
        ("PUT /ISAPI/PTZCtrl/channels/1/start", "Iniciar movimiento PTZ"),
        ("PUT /ISAPI/PTZCtrl/channels/1/stop", "Detener movimiento PTZ"),
        ("GET /ISAPI/Security/UserCheck", "Verificar autenticación de usuario"),
        ("GET /ISAPI/Security/userList", "Lista de usuarios del dispositivo"),
        ("GET /ISAPI/System/IO/outputs/1", "Estado de salidas de relé"),
        ("PUT /ISAPI/System/IO/outputs/1", "Activar/desactivar relé"),
        ("GET /ISAPI/System/IO/inputs/1", "Estado de entradas de alarma"),
        ("GET /ISAPI/Intelligent/FDLib", "Detección facial / biblioteca de rostros"),
        ("GET /ISAPI/Intelligent/channels/1", "Analíticos inteligentes del canal"),
        ("PUT /ISAPI/System/reboot", "Reiniciar el dispositivo"),
        ("GET /ISAPI/AccessControl/UserRecord", "Registros de control de acceso"),
        ("GET /ISAPI/AccessControl/Door/status/1", "Estado de puerta (control de acceso)"),
        ("PUT /ISAPI/AccessControl/RemoteControl/door/1", "Abrir/cerrar puerta remotamente"),
        ("GET /ISAPI/System/log", "Logs del sistema"),
        ("GET /ISAPI/System/upgrade", "Estado de actualización de firmware"),
    ],
    "🔵 Dahua CGI": [
        ("/cgi-bin/magicBox.cgi?action=getSystemInfo", "Info del sistema (serial, tipo, versión)"),
        ("/cgi-bin/param.cgi?command=getDeviceType", "Tipo de dispositivo (DVR/NVR/IPC)"),
        ("/cgi-bin/param.cgi?command=getProductInfo", "Info de producto y fabricante"),
        ("/cgi-bin/configManager.cgi?action=getConfig&name=Network", "Configuración de red"),
        ("/cgi-bin/configManager.cgi?action=getConfig&name=Video", "Configuración de video"),
        ("/cgi-bin/configManager.cgi?action=getConfig&name=Record", "Configuración de grabación"),
        ("/cgi-bin/configManager.cgi?action=getConfig&name=Ptz", "Configuración PTZ"),
        ("/cgi-bin/snapshot.cgi?channel=1", "Capturar snapshot del canal 1"),
        ("/cgi-bin/snapshot.cgi?channel=1&type=JPEG", "Snapshot en JPEG forzado"),
        ("/cgi-bin/record.cgi?action=start&channel=1", "Iniciar grabación manual en canal 1"),
        ("/cgi-bin/record.cgi?action=stop&channel=1", "Detener grabación manual"),
        ("/cgi-bin/ptz.cgi?action=start&code=Up&channel=1", "Mover PTZ hacia arriba"),
        ("/cgi-bin/ptz.cgi?action=start&code=Down&channel=1", "Mover PTZ hacia abajo"),
        ("/cgi-bin/ptz.cgi?action=start&code=Left&channel=1", "Mover PTZ hacia izquierda"),
        ("/cgi-bin/ptz.cgi?action=start&code=Right&channel=1", "Mover PTZ hacia derecha"),
        ("/cgi-bin/ptz.cgi?action=start&code=ZoomIn&channel=1", "Zoom in PTZ"),
        ("/cgi-bin/ptz.cgi?action=start&code=ZoomOut&channel=1", "Zoom out PTZ"),
        ("/cgi-bin/ptz.cgi?action=start&code=FocusFar&channel=1", "Enfoque lejano PTZ"),
        ("/cgi-bin/ptz.cgi?action=start&code=FocusNear&channel=1", "Enfoque cercano PTZ"),
        ("/cgi-bin/ptz.cgi?action=stop&channel=1", "Detener movimiento PTZ"),
        ("/cgi-bin/ptz.cgi?action=preset&channel=1&preset=1", "Ir a preset 1"),
        ("/cgi-bin/ptz.cgi?action=setPreset&channel=1&preset=1", "Guardar preset 1"),
        ("/cgi-bin/ptz.cgi?action=clearPreset&channel=1&preset=1", "Borrar preset 1"),
        ("/cgi-bin/eventManager.cgi?action=attach&codes=[All]", "Adjuntar todos los eventos"),
        ("/cgi-bin/eventManager.cgi?action=attach&codes=[VideoMotion]", "Eventos de detección de movimiento"),
        ("/cgi-bin/eventManager.cgi?action=attach&codes=[VideoLoss]", "Eventos de pérdida de video"),
        ("/cgi-bin/eventManager.cgi?action=attach&codes=[VideoBlind]", "Eventos de bloqueo de cámara"),
        ("/cgi-bin/alarm.cgi?action=getStatus", "Estado de alarmas"),
        ("/cgi-bin/alarm.cgi?action=getAlarmRecord", "Historial de alarmas"),
        ("/cgi-bin/storageManager.cgi?action=query&type=hddInfo", "Información de HDD"),
        ("/cgi-bin/storageManager.cgi?action=query&type=hardDisk", "Lista de discos duros"),
        ("/cgi-bin/storageManager.cgi?action=format&type=HDD&id=1", "Formatear HDD (cuidado)"),
        ("/cgi-bin/accessControl.cgi?action=openDoor&channel=1", "Abrir puerta (control acceso)"),
        ("/cgi-bin/accessControl.cgi?action=closeDoor&channel=1", "Cerrar puerta"),
        ("/cgi-bin/accessControl.cgi?action=getDoorStatus&channel=1", "Estado de puerta"),
        ("/cgi-bin/accountManager.cgi?action=query", "Lista de cuentas de usuario"),
        ("/cgi-bin/accountManager.cgi?action=create&user=...", "Crear usuario"),
        ("/cgi-bin/accountManager.cgi?action=delete&user=...", "Eliminar usuario"),
        ("/cgi-bin/accountManager.cgi?action=modify&user=...", "Modificar usuario"),
        ("/cgi-bin/log.cgi?action=query&count=50", "Logs del sistema (últimos 50)"),
        ("/cgi-bin/log.cgi?action=query&count=200&type=alarm", "Logs de alarma"),
        ("/cgi-bin/magicBox.cgi?action=reboot", "Reiniciar el dispositivo"),
        ("/cgi-bin/magicBox.cgi?action=getDeviceAllInfo", "Toda la info del dispositivo"),
        ("/cgi-bin/magicBox.cgi?action=getHardwareVersion", "Versión de hardware"),
        ("/cgi-bin/magicBox.cgi?action=upgrade", "Actualizar firmware (subir archivo)"),
        ("/cgi-bin/configManager.cgi?action=setConfig&name=...", "Cambiar configuración"),
        ("/cgi-bin/encode.cgi?action=getConfigs", "Configuración de codificación"),
        ("/cgi-bin/encode.cgi?action=getCaps", "Capacidades de codificación"),
        ("/cgi-bin/audio.cgi?action=getAudioConfig", "Configuración de audio"),
    ],
    "🟢 ZKTeco HTTP": [
        ("GET /iclock/deviceinfo", "Información del dispositivo biométrico"),
        ("GET /iclock/syncdatetime", "Sincronizar hora con el servidor"),
        ("GET /iclock/settime?Y=...&M=...&D=...&H=...&m=...&S=...", "Configurar hora manualmente"),
        ("GET /iclock/getrequest", "Obtener datos de marcación pendientes"),
        ("GET /iclock/records", "Obtener registros de marcación (asistencia)"),
        ("GET /iclock/cdata", "Subir datos de marcación al dispositivo"),
        ("GET /iclock/operlog", "Log de operaciones del dispositivo"),
        ("GET /iclock/devcmd?command=comando", "Enviar comando al dispositivo"),
        ("GET /iclock/devcmd?command=door1_open", "Abrir puerta 1"),
        ("GET /iclock/devcmd?command=door1_close", "Cerrar puerta 1"),
        ("GET /iclock/devcmd?command=door2_open", "Abrir puerta 2"),
        ("GET /iclock/devcmd?command=doorstatus", "Estado de todas las puertas"),
        ("GET /iclock/devcmd?command=restart", "Reiniciar el dispositivo"),
        ("GET /iclock/devcmd?command=clearadmin", "Limpiar contraseña de admin"),
        ("GET /iclock/devcmd?command=clearoplog", "Limpiar log de operaciones"),
        ("GET /iclock/devcmd?command=clrdata", "Limpiar todos los datos de asistencia"),
        ("GET /iclock/devcmd?command=enableclock", "Habilitar modo reloj"),
        ("GET /iclock/devcmd?command=disableclock", "Deshabilitar modo reloj"),
        ("GET /iclock/atcommand.axd", "Comando administrativo avanzado"),
        ("GET /iclock/devicecmd", "Comando desde servidor (push)"),
        ("GET /iclock/fmtcache", "Limpiar caché de asistencia"),
        ("GET /iclock/systeminfo", "Info del sistema (versión firmware)"),
        ("GET /iclock/smsetting", "Configuración de SMS (si aplica)"),
        ("GET /iclock/serialnumber", "Número de serie del dispositivo"),
        ("GET /iclock/fpinfo", "Información de huellas almacenadas"),
        ("GET /iclock/fpcount", "Cantidad de huellas registradas"),
        ("GET /iclock/usercount", "Cantidad de usuarios registrados"),
        ("GET /iclock/facesetting", "Configuración de reconocimiento facial"),
        ("GET /personnel/api/employees", "Lista de empleados (REST API)"),
        ("GET /personnel/api/transactions", "Transacciones (REST API)"),
        ("GET /device/rest/attTransactions", "Transacciones de asistencia (REST)"),
        ("GET /device/rest/employees", "Empleados (REST)"),
        ("GET /device/rest/departments", "Departamentos (REST)"),
        ("GET /device/rest/attendance/records", "Registros de asistencia (REST)"),
        ("GET /device/rest/person/info?personId=...", "Info de persona por ID (REST)"),
    ],
    "🔧 Diagnóstico CCTV": [
        ("ping CAMARA_IP", "Verificar conectividad básica"),
        ("nmap -p 80,443,554,8000,37777,8080,8200 CAMARA_IP", "Escanear puertos CCTV comunes"),
        ("nmap -sV -p 80,443,554 CAMARA_IP", "Detección de versión de servicios"),
        ("nmap -O --osscan-guess CAMARA_IP", "Detección de sistema operativo"),
        ("curl -I http://CAMARA_IP", "Ver cabeceras HTTP (identificar vendor)"),
        ("curl -s http://CAMARA_IP/ISAPI/System/deviceInfo -u admin:12345", "Probar ISAPI manualmente"),
        ("curl -s http://CAMARA_IP/cgi-bin/magicBox.cgi?action=getSystemInfo -u admin:admin", "Probar Dahua CGI manualmente"),
        ("curl -s http://CAMARA_IP/iclock/deviceinfo -u admin:admin", "Probar ZKTeco manualmente"),
        ("curl -s -o /dev/null -w '%{http_code}' http://CAMARA_IP/onvif/device_service", "Verificar si ONVIF responde"),
        ("curl -s --digest http://CAMARA_IP/ISAPI/System/deviceInfo -u admin:12345", "Probar ISAPI con Digest auth"),
        ("wget -O test.jpg http://CAMARA_IP/ISAPI/Streaming/channels/1/picture --user=admin --password=12345", "Descargar snapshot"),
        ("ffprobe rtsp://admin:12345@CAMARA_IP:554/Streaming/Channels/101", "Analizar stream RTSP con ffprobe"),
        ("tcpdump -i eth0 port 554", "Capturar tráfico RTSP"),
        ("tcpdump -i eth0 port 80", "Capturar tráfico HTTP de cámara"),
        ("arping CAMARA_IP", "Verificar MAC por ARP (red local)"),
        ("nc -zv CAMARA_IP 554", "Probar puerto RTSP con netcat"),
        ("nc -zv CAMARA_IP 80", "Probar puerto HTTP con netcat"),
    ],
}
