FORTINET_COMMANDS = {
    "Básicos": [
        ("show system status", "Estado del sistema FortiGate"),
        ("show system version", "Versión de FortiOS"),
        ("show system interface", "Mostrar interfaces"),
        ("show system dns", "Configuración DNS"),
        ("show system route", "Tabla de enrutamiento"),
        ("show system admin", "Administradores"),
        ("config system global", "Configuración global"),
        ("set hostname FGT-01", "Cambiar nombre del equipo"),
        ("set admintimeout 120", "Timeout de administración"),
        ("end", "Salir de configuración"),
        ("execute shutdown", "Apagar el equipo"),
        ("execute reboot", "Reiniciar el equipo"),
        ("execute backup config tftp archivo.conf 192.168.1.100", "Backup a TFTP"),
        ("execute restore config tftp archivo.conf 192.168.1.100", "Restaurar config"),
        ("get system performance status", "Rendimiento del sistema"),
    ],
    "Interfaces": [
        ("config system interface", "Configurar interfaces"),
        ("edit port1", "Editar interfaz port1"),
        ("set mode static", "Modo estático"),
        ("set ip 10.0.0.1 255.255.255.252", "Asignar IP"),
        ("set allowaccess ping https ssh", "Permitir accesos"),
        ("set description WAN-ISP", "Descripción de interfaz"),
        ("set speed 1000full", "Velocidad/dúplex"),
        ("next", "Siguiente interfaz"),
        ("config system virtual-switch", "Configurar switch virtual"),
        ("append port1", "Agregar puerto a switch"),
        ("show system interface physical", "Interfaces físicas"),
        ("diagnose hardware deviceinfo nic port1", "Información detallada NIC"),
    ],
    "Firewall / Políticas": [
        ("config firewall policy", "Configurar políticas de firewall"),
        ("edit 0", "Crear nueva política"),
        ("set name PERMITIR-HTTP", "Nombre de la política"),
        ("set srcintf port2", "Interfaz origen"),
        ("set dstintf port1", "Interfaz destino"),
        ("set srcaddr all", "Dirección origen"),
        ("set dstaddr all", "Dirección destino"),
        ("set action accept", "Acción (accept/deny)"),
        ("set schedule always", "Programación"),
        ("set service HTTP", "Servicio permitido"),
        ("set logtraffic all", "Logging de tráfico"),
        ("set nat enable", "Habilitar NAT"),
        ("next", "Guardar y continuar"),
        ("show firewall policy", "Mostrar políticas"),
        ("diagnose firewall iprope list 100000", "Mostrar reglas de firewall cargadas"),
    ],
    "NAT": [
        ("config firewall ippool", "Pool de IPs para NAT"),
        ("edit POOL1", "Crear pool"),
        ("set type overload", "Tipo overload (PAT)"),
        ("set startip 203.0.113.10", "IP inicial del pool"),
        ("set endip 203.0.113.20", "IP final del pool"),
        ("config firewall vip", "Virtual IP (DNAT)"),
        ("edit MI-VIP", "Crear VIP"),
        ("set extip 203.0.113.5", "IP pública"),
        ("set mappedip 192.168.1.10", "IP privada"),
        ("set extintf port1", "Interfaz externa"),
        ("set portforward enable", "Redirección de puertos"),
        ("set protocol tcp", "Protocolo"),
        ("set extport 80", "Puerto externo"),
        ("set mappedport 80", "Puerto interno"),
    ],
    "VPN IPSec": [
        ("config vpn ipsec phase1-interface", "Configurar Phase 1"),
        ("edit VPN-P1", "Nombre Phase 1"),
        ("set interface port1", "Interfaz de salida"),
        ("set peertype any", "Tipo de peer"),
        ("set net-device enable", "Habilitar device"),
        ("set proposal aes256-sha256", "Propuesta de cifrado"),
        ("set dhgrp 14", "Grupo Diffie-Hellman"),
        ("set remote-gw 203.0.113.1", "Gateway remoto"),
        ("set psksecret MIPASS", "Clave pre-compartida"),
        ("config vpn ipsec phase2-interface", "Configurar Phase 2"),
        ("edit VPN-P2", "Nombre Phase 2"),
        ("set phase1name VPN-P1", "Phase 1 asociada"),
        ("set proposal aes256-sha256", "Propuesta Phase 2"),
        ("set src-addr-type subnet", "Tipo de red origen"),
        ("set src-subnet 192.168.1.0 255.255.255.0", "Red local"),
        ("set dst-addr-type subnet", "Tipo de red destino"),
        ("set dst-subnet 10.0.0.0 255.255.255.0", "Red remota"),
        ("set auto-negotiate enable", "Auto-negotiate"),
        ("diagnose vpn ike gateway list", "Estado de VPN IKE"),
        ("diagnose vpn tunnel list", "Túneles activos"),
    ],
    "SSL VPN": [
        ("config vpn ssl settings", "Configuración SSL VPN"),
        ("set tunnel-ip-pools SSL-VPN-POOL", "Pool de IPs"),
        ("set port 443", "Puerto SSL VPN"),
        ("config vpn ssl web portal", "Portal web SSL VPN"),
        ("edit full-access", "Portal full access"),
        ("set tunnel-mode enable", "Modo túnel"),
        ("set web-mode enable", "Modo web"),
        ("set split-tunneling enable", "Split tunneling"),
        ("config user group", "Grupo de usuarios"),
        ("edit VPN-USERS", "Crear grupo"),
        ("set member guest", "Configurar miembros"),
        ("config firewall policy", "Política SSL VPN"),
        ("set srcintf ssl.root", "Interfaz origen SSL VPN"),
    ],
    "Routing": [
        ("config router static", "Rutas estáticas"),
        ("edit 0", "Crear ruta"),
        ("set device port1", "Interfaz de salida"),
        ("set gateway 10.0.0.2", "Gateway"),
        ("set dst 0.0.0.0 0.0.0.0", "Destino (default)"),
        ("config router ospf", "Configurar OSPF"),
        ("set router-id 1.1.1.1", "Router ID"),
        ("config router ospf area", "Áreas OSPF"),
        ("edit 0.0.0.0", "Área backbone"),
        ("config router ospf network", "Redes OSPF"),
        ("edit 192.168.1.0 255.255.255.0", "Red a anunciar"),
        ("set area 0.0.0.0", "Área"),
        ("config router bgp", "Configurar BGP"),
        ("set as 65000", "AS local"),
        ("config router bgp neighbor", "Vecino BGP"),
        ("edit 10.0.0.2", "IP del vecino"),
        ("set remote-as 65001", "AS remoto"),
        ("set route-map-out RM-EXPORT", "Route map de salida"),
    ],
    "Diagnóstico": [
        ("diagnose sys top", "Procesos en tiempo real"),
        ("diagnose sys top 5 30", "Top procesos cada 5s, 30 veces"),
        ("diagnose debug flow trace start", "Debug de flujo"),
        ("diagnose debug flow filter addr 192.168.1.10", "Filtro depuración"),
        ("diagnose debug flow filter proto 6", "Filtrar por protocolo"),
        ("diagnose debug flow filter port 80", "Filtrar por puerto"),
        ("diagnose debug enable", "Activar debug"),
        ("diagnose debug disable", "Desactivar debug"),
        ("execute ping 8.8.8.8", "Ping"),
        ("execute traceroute 8.8.8.8", "Traceroute"),
        ("execute telnet 192.168.1.1", "Telnet"),
        ("execute ssh admin@192.168.1.1", "SSH"),
        ("diagnose sniffer packet port1 'tcp port 80' 3", "Sniffer de paquetes"),
        ("diagnose sys session list", "Sesiones activas"),
        ("get router info routing-table all", "Tabla de enrutamiento"),
        ("show full-configuration", "Configuración completa"),
        ("diagnose hardware sysinfo memory", "Uso de memoria"),
        ("diagnose hardware sysinfo cpu", "Uso de CPU"),
    ],
}
