LINUX_COMMANDS = {
    "Archivos y Directorios": [
        ("ls", "Lista archivos y directorios"),
        ("ls -la", "Lista detallada incluyendo ocultos"),
        ("ls -lh", "Lista con tamaños legibles"),
        ("pwd", "Muestra el directorio actual"),
        ("cd <dir>", "Cambia al directorio especificado"),
        ("cd ..", "Sube un nivel en el árbol de directorios"),
        ("cd ~", "Va al directorio home del usuario"),
        ("cd -", "Va al directorio anterior"),
        ("mkdir <dir>", "Crea un directorio"),
        ("mkdir -p <dir>/<dir>", "Crea directorios anidados"),
        ("rmdir <dir>", "Elimina un directorio vacío"),
        ("rm <file>", "Elimina un archivo"),
        ("rm -r <dir>", "Elimina recursivamente un directorio"),
        ("rm -rf <dir>", "Elimina forzadamente sin preguntar"),
        ("cp <origen> <dest>", "Copia archivos o directorios"),
        ("cp -r <origen> <dest>", "Copia recursivamente"),
        ("cp -a <origen> <dest>", "Copia preservando atributos"),
        ("mv <origen> <dest>", "Mueve o renombra archivos"),
        ("mv -i <origen> <dest>", "Pregunta antes de sobrescribir"),
        ("touch <file>", "Crea archivo vacío o actualiza timestamp"),
        ("cat <file>", "Muestra el contenido de un archivo"),
        ("tac <file>", "Muestra contenido en orden inverso"),
        ("more <file>", "Visualiza archivo por páginas"),
        ("less <file>", "Visualiza archivo con navegación"),
        ("head <file>", "Muestra las primeras 10 líneas"),
        ("head -n 20 <file>", "Muestra las primeras 20 líneas"),
        ("tail <file>", "Muestra las últimas 10 líneas"),
        ("tail -f <file>", "Sigue el archivo en tiempo real"),
        ("nl <file>", "Numera las líneas del archivo"),
        ("file <file>", "Determina el tipo de archivo"),
        ("stat <file>", "Muestra estadísticas del archivo"),
        ("ln -s <target> <link>", "Crea un enlace simbólico"),
        ("ln <target> <link>", "Crea un enlace duro"),
        ("readlink <link>", "Muestra el destino de un enlace"),
        ("basename <path>", "Extrae el nombre del archivo de una ruta"),
        ("dirname <path>", "Extrae el directorio de una ruta"),
        ("diff <f1> <f2>", "Compara dos archivos línea por línea"),
        ("diff -r <d1> <d2>", "Compara directorios recursivamente"),
        ("sort <file>", "Ordena líneas de un archivo"),
        ("uniq <file>", "Elimina líneas duplicadas consecutivas"),
        ("wc <file>", "Cuenta líneas, palabras y caracteres"),
        ("wc -l <file>", "Cuenta solo líneas"),
        ("tree", "Muestra estructura de directorios en árbol"),
        ("tree -L 2", "Árbol con profundidad máxima 2"),
        ("du <dir>", "Muestra uso de disco por directorio"),
        ("du -sh <dir>", "Muestra tamaño total en formato legible"),
        ("df -h", "Muestra espacio en discos montados"),
        ("realpath <file>", "Resuelve la ruta absoluta"),
        ("truncate -s 0 <file>", "Vacía el contenido del archivo"),
        ("split -l 100 <file>", "Divide archivo en partes de 100 líneas"),
        ("findmnt", "Muestra árbol de sistemas montados"),
        ("lsblk", "Lista dispositivos de bloque"),
        ("blkid", "Muestra UUID y tipo de dispositivos"),
        ("mount <device> <mountpoint>", "Monta un sistema de archivos"),
        ("umount <mountpoint>", "Desmonta un sistema de archivos"),
    ],
    "Procesos": [
        ("ps", "Lista procesos de la sesión actual"),
        ("ps aux", "Lista todos los procesos del sistema"),
        ("ps -ef", "Lista procesos con formato completo"),
        ("ps -eo pid,ppid,cmd,%mem,%cpu", "Lista procesos con columnas personalizadas"),
        ("top", "Monitor de procesos en tiempo real"),
        ("htop", "Monitor interactivo de procesos"),
        ("pgrep <name>", "Busca PID por nombre"),
        ("pkill <name>", "Mata procesos por nombre"),
        ("kill <PID>", "Envía señal SIGTERM a un proceso"),
        ("kill -9 <PID>", "Mata proceso forzadamente (SIGKILL)"),
        ("kill -15 <PID>", "Termina proceso amablemente (SIGTERM)"),
        ("killall <name>", "Mata todos los procesos con ese nombre"),
        ("pstree", "Muestra procesos en árbol"),
        ("pidof <name>", "Obtiene el PID de un proceso"),
        ("nice -n 10 <cmd>", "Ejecuta con prioridad baja"),
        ("renice -n 5 -p <PID>", "Cambia prioridad de proceso"),
        ("nohup <cmd> &", "Ejecuta proceso ignorando HUP en segundo plano"),
        ("&", "Ejecuta comando en segundo plano"),
        ("jobs", "Lista trabajos en segundo plano"),
        ("fg %<n>", "Trae trabajo al primer plano"),
        ("bg %<n>", "Envía trabajo a segundo plano"),
        ("disown <PID>", "Elimina proceso de la tabla de trabajos"),
        ("wait <PID>", "Espera a que un proceso termine"),
        ("screen", "Terminal multiplexor con sesiones persistentes"),
        ("screen -ls", "Lista sesiones de screen"),
        ("screen -r <id>", "Reanuda sesión de screen"),
        ("tmux", "Terminal multiplexor moderno"),
        ("tmux ls", "Lista sesiones de tmux"),
        ("tmux attach -t <id>", "Se conecta a sesión tmux"),
        ("uptime", "Muestra tiempo de actividad del sistema"),
        ("mpstat", "Estadísticas de uso de CPU"),
        ("time <cmd>", "Mide el tiempo de ejecución de un comando"),
        ("lsof", "Lista archivos abiertos por procesos"),
        ("lsof -i :<port>", "Procesos usando un puerto específico"),
        ("fuser <file>", "Muestra PIDs que usan un archivo"),
        ("fuser -k <port>/tcp", "Mata procesos usando un puerto"),
        ("taskset -c <cpu> <cmd>", "Ejecuta comando en CPU específica"),
        ("systemd-cgls", "Muestra árbol de control groups"),
    ],
    "Red": [
        ("ip a", "Muestra interfaces de red con direcciones"),
        ("ip link", "Lista interfaces de red"),
        ("ip link set <if> up/down", "Activa/desactiva interfaz"),
        ("ip addr add <cidr> dev <if>", "Añade IP a una interfaz"),
        ("ip route", "Muestra tabla de enrutamiento"),
        ("ip route add default via <gw>", "Añade ruta por defecto"),
        ("ip neigh", "Muestra tabla ARP/NDP"),
        ("ss -tuln", "Muestra puertos TCP/UDP en escucha"),
        ("ss -tp", "Muestra conexiones TCP con procesos"),
        ("netstat -tuln", "Muestra puertos en escucha (obsoleto)"),
        ("netstat -i", "Muestra estadísticas de interfaces"),
        ("ping <host>", "Prueba conectividad básica"),
        ("ping -c 5 <host>", "Envía 5 paquetes ICMP"),
        ("traceroute <host>", "Rastro de ruta hasta el destino"),
        ("mtr <host>", "Combinación traceroute + ping en tiempo real"),
        ("nslookup <domain>", "Consulta DNS"),
        ("dig <domain>", "Consulta DNS avanzada"),
        ("dig -x <ip>", "Consulta DNS inversa"),
        ("host <domain>", "Resuelve nombre a IP"),
        ("whois <domain>", "Información WHOIS de dominio"),
        ("curl <url>", "Transfiere datos desde/hacia servidores"),
        ("curl -I <url>", "Muestra solo cabeceras HTTP"),
        ("curl -O <url>", "Descarga archivo remoto"),
        ("wget <url>", "Descarga archivos desde internet"),
        ("wget -r <url>", "Descarga recursiva"),
        ("wget -c <url>", "Reanuda descarga interrumpida"),
        ("nc <host> <port>", "Conexión TCP genérica"),
        ("nc -l -p <port>", "Escucha en un puerto TCP"),
        ("nc -z -v <host> <port-range>", "Escanea puertos TCP"),
        ("nmap <host>", "Escáner de puertos y servicios"),
        ("nmap -sS <host>", "Escaneo SYN sigiloso"),
        ("nmap -sV <host>", "Detecta versiones de servicios"),
        ("tcpdump -i <if>", "Captura paquetes en interfaz"),
        ("tcpdump port 80", "Captura tráfico HTTP"),
        ("tcpdump -X", "Muestra paquetes en hex y ASCII"),
        ("ipcalc <cidr>", "Calcula direccionamiento IP"),
        ("nmcli dev status", "Estado de dispositivos de red"),
        ("nmcli con show", "Lista conexiones de NetworkManager"),
        ("nmcli con up/down <id>", "Activa/desactiva conexión"),
        ("hostname", "Muestra nombre del host"),
        ("hostnamectl set-hostname <n>", "Cambia hostname"),
        ("resolvectl status", "Estado de resolución DNS"),
        ("tc qdisc show", "Muestra disciplinas de cola"),
        ("ethtool <if>", "Información detallada de interfaz"),
        ("iwconfig", "Configuración de interfaces inalámbricas"),
        ("iperf3 -s", "Servidor iperf para pruebas de ancho de banda"),
        ("iperf3 -c <host>", "Cliente iperf para prueba de ancho de banda"),
        ("ssh <user>@<host>", "Conexión SSH remota"),
    ],
    "Discos y Sistema": [
        ("df -h", "Uso de discos en formato legible"),
        ("df -i", "Muestra uso de inodos"),
        ("du -sh <dir>", "Tamaño total de un directorio"),
        ("du -h --max-depth=1", "Tamaño por subdirectorio nivel 1"),
        ("fdisk -l", "Lista particiones de discos"),
        ("fdisk /dev/sda", "Gestiona particiones"),
        ("parted /dev/sda print", "Muestra tabla de particiones"),
        ("mkfs.ext4 /dev/sda1", "Formatea como ext4"),
        ("mkfs.xfs /dev/sda1", "Formatea como XFS"),
        ("mount <dev> <dir>", "Monta dispositivo en directorio"),
        ("umount <dir>", "Desmonta sistema de archivos"),
        ("lsblk", "Lista dispositivos de bloque"),
        ("blkid", "UUID y tipo de sistema de archivos"),
        ("tune2fs -l /dev/sda1", "Parámetros del sistema ext"),
        ("resize2fs /dev/sda1", "Redimensiona sistema ext4"),
        ("xfs_info /dev/sda1", "Información del sistema XFS"),
        ("xfs_growfs /mountpoint", "Expande sistema XFS"),
        ("fsck /dev/sda1", "Verifica y repara sistema de archivos"),
        ("smartctl -a /dev/sda", "Información S.M.A.R.T. del disco"),
        ("smartctl -t short /dev/sda", "Test rápido S.M.A.R.T."),
        ("dd if=/dev/sda of=backup.img", "Copia disco bit a bit"),
        ("dd if=/dev/zero of=file bs=1M count=100", "Crea archivo de 100MB"),
        ("pv <file> > /dev/sda", "dd con barra de progreso"),
        ("sync", "Vuelca búferes de escritura a disco"),
        ("hdparm -tT /dev/sda", "Prueba velocidad de lectura"),
        ("badblocks -v /dev/sda", "Busca bloques dañados"),
        ("lvm", "Gestión de volúmenes lógicos"),
        ("pvcreate /dev/sda1", "Crea physical volume LVM"),
        ("vgcreate vg0 /dev/sda1", "Crea volume group LVM"),
        ("lvcreate -L 10G -n lv0 vg0", "Crea logical volume LVM"),
        ("lvresize -L +5G vg0/lv0", "Aumenta tamaño LV"),
        ("lvextend -l +100%FREE vg0/lv0", "Extiende LV al espacio libre"),
        ("uname -a", "Toda la información del kernel"),
        ("uname -r", "Versión del kernel"),
        ("lsb_release -a", "Información de distribución"),
        ("cat /etc/os-release", "Información del SO"),
        ("lsmod", "Módulos cargados en el kernel"),
        ("modinfo <module>", "Información de un módulo"),
        ("modprobe <module>", "Carga módulo del kernel"),
        ("modprobe -r <module>", "Descarga módulo"),
        ("dmesg", "Mensajes del kernel"),
        ("dmesg -w", "Sigue mensajes en tiempo real"),
        ("sysctl -a", "Todos los parámetros del kernel"),
        ("sysctl -w <param>=<val>", "Cambia parámetro del kernel"),
        ("dmidecode", "Información del hardware"),
        ("dmidecode -t memory", "Información de memorias RAM"),
        ("lscpu", "Información de la CPU"),
        ("lspci", "Dispositivos PCI conectados"),
        ("lsusb", "Dispositivos USB conectados"),
        ("lshw", "Información completa del hardware"),
    ],
    "Usuarios y Permisos": [
        ("whoami", "Usuario actual"),
        ("id", "UID, GID y grupos del usuario"),
        ("who", "Usuarios logueados en el sistema"),
        ("w", "Usuarios logueados y qué hacen"),
        ("users", "Lista nombres de usuarios conectados"),
        ("last", "Últimos inicios de sesión"),
        ("lastb", "Últimos intentos fallidos de login"),
        ("useradd <user>", "Crea un usuario nuevo"),
        ("useradd -m -G <group> <user>", "Crea usuario con home y grupo"),
        ("usermod -aG <group> <user>", "Añade usuario a grupo"),
        ("usermod -s /bin/bash <user>", "Cambia shell del usuario"),
        ("usermod -L <user>", "Bloquea cuenta de usuario"),
        ("usermod -U <user>", "Desbloquea cuenta de usuario"),
        ("userdel <user>", "Elimina un usuario"),
        ("userdel -r <user>", "Elimina usuario y su home"),
        ("passwd", "Cambia contraseña del usuario actual"),
        ("passwd <user>", "Cambia contraseña de otro usuario"),
        ("chage -l <user>", "Información de expiración de contraseña"),
        ("chage -E 2025-12-31 <user>", "Establece fecha de expiración"),
        ("groupadd <group>", "Crea un grupo"),
        ("groupdel <group>", "Elimina un grupo"),
        ("groups <user>", "Grupos del usuario"),
        ("chmod 755 <file>", "Permisos rwxr-xr-x"),
        ("chmod u+x <file>", "Añade ejecución al propietario"),
        ("chmod -R 755 <dir>", "Cambia permisos recursivamente"),
        ("chown <user>:<group> <file>", "Cambia propietario y grupo"),
        ("chown -R <user> <dir>", "Cambia propietario recursivamente"),
        ("chgrp <group> <file>", "Cambia grupo del archivo"),
        ("umask 022", "Establece máscara de permisos por defecto"),
        ("getfacl <file>", "Muestra ACLs de un archivo"),
        ("setfacl -m u:<user>:rwx <file>", "Asigna ACL a usuario"),
        ("setfacl -x u:<user> <file>", "Elimina ACL de usuario"),
        ("su - <user>", "Cambia de usuario"),
        ("sudo -i", "Inicia sesión como root"),
        ("sudo -l", "Lista comandos sudo permitidos"),
        ("sudo -u <user> <cmd>", "Ejecuta comando como otro usuario"),
        ("visudo", "Edita sudoers de forma segura"),
    ],
    "Compresión y Archivos": [
        ("tar -cvf <file.tar> <dir>", "Crea tar sin comprimir"),
        ("tar -xvf <file.tar>", "Extrae tar"),
        ("tar -tf <file.tar>", "Lista contenido del tar"),
        ("tar -czvf <file.tar.gz> <dir>", "Crea tar comprimido con gzip"),
        ("tar -xzvf <file.tar.gz>", "Extrae tar.gz"),
        ("tar -cjvf <file.tar.bz2> <dir>", "Crea tar comprimido con bzip2"),
        ("tar -xjvf <file.tar.bz2>", "Extrae tar.bz2"),
        ("tar -cJvf <file.tar.xz> <dir>", "Crea tar comprimido con xz"),
        ("tar -xJvf <file.tar.xz>", "Extrae tar.xz"),
        ("gzip <file>", "Comprime archivo con gzip"),
        ("gunzip <file.gz>", "Descomprime gzip"),
        ("bzip2 <file>", "Comprime archivo con bzip2"),
        ("bunzip2 <file.bz2>", "Descomprime bzip2"),
        ("xz <file>", "Comprime archivo con xz"),
        ("unxz <file.xz>", "Descomprime xz"),
        ("zip -r <file.zip> <dir>", "Crea archivo zip"),
        ("unzip <file.zip>", "Descomprime zip"),
        ("unzip -l <file.zip>", "Lista contenido del zip"),
        ("7z a <file.7z> <dir>", "Comprime con 7z"),
        ("7z x <file.7z>", "Descomprime 7z"),
        ("zcat <file.gz>", "Lee contenido de gzip sin descomprimir"),
        ("zless <file.gz>", "Navega contenido gzip"),
        ("zgrep <pattern> <file.gz>", "Busca patrón en gzip"),
    ],
    "Búsqueda y Texto": [
        ("find <dir> -name <pattern>", "Busca archivos por nombre"),
        ("find <dir> -type f", "Busca solo archivos regulares"),
        ("find <dir> -type d", "Busca solo directorios"),
        ("find <dir> -size +100M", "Archivos mayores a 100MB"),
        ("find <dir> -mtime -7", "Archivos modificados en últimos 7 días"),
        ("find <dir> -exec <cmd> {} \\;", "Ejecuta comando sobre resultados"),
        ("find <dir> -name '*.py' | xargs <cmd>", "Pasa resultados a xargs"),
        ("locate <pattern>", "Busca archivos por índice (mlocate)"),
        ("updatedb", "Actualiza base de datos de locate"),
        ("grep <pattern> <file>", "Busca patrón en archivo"),
        ("grep -i <pattern> <file>", "Búsqueda insensible a mayúsculas"),
        ("grep -r <pattern> <dir>", "Busca recursivamente en directorio"),
        ("grep -v <pattern> <file>", "Muestra líneas que NO coinciden"),
        ("grep -c <pattern> <file>", "Cuenta coincidencias"),
        ("grep -n <pattern> <file>", "Muestra número de línea"),
        ("grep -E <regex> <file>", "Usa expresión regular extendida"),
        ("egrep <pattern> <file>", "Equivalente a grep -E"),
        ("fgrep <pattern> <file>", "Busca literal (sin regex)"),
        ("rg <pattern>", "ripgrep - búsqueda rápida"),
        ("rg -i <pattern>", "ripgrep insensible a mayúsculas"),
        ("rg --type py <pattern>", "ripgrep solo archivos Python"),
        ("ack <pattern>", "ack - búsqueda para programadores"),
        ("ag <pattern>", "silver surfer - búsqueda ultrarrápida"),
        ("sed 's/a/b/g' <file>", "Reemplaza a por b globalmente"),
        ("sed -n '5,10p' <file>", "Imprime líneas 5 a 10"),
        ("sed '/pat/d' <file>", "Elimina líneas que contienen patrón"),
        ("awk '{print \$1}' <file>", "Imprime primera columna"),
        ("awk -F: '{print \$1,\$3}' <file>", "Divide por dos puntos"),
        ("awk '{sum+=\$1} END{print sum}'", "Suma valores de primera columna"),
        ("cut -d: -f1 <file>", "Extrae campo 1 separado por :"),
        ("cut -c1-10 <file>", "Extrae primeros 10 caracteres"),
        ("tr 'a-z' 'A-Z' < <file>", "Convierte a mayúsculas"),
        ("tr -d '\\n' < <file>", "Elimina saltos de línea"),
        ("paste <f1> <f2>", "Combina archivos línea a línea"),
        ("join <f1> <f2>", "Combina líneas por campo común"),
    ],
    "Monitorización y Logs": [
        ("journalctl", "Muestra logs del sistema con systemd"),
        ("journalctl -u <service>", "Logs de un servicio específico"),
        ("journalctl -f", "Sigue logs en tiempo real"),
        ("journalctl --since '1 hour ago'", "Logs de la última hora"),
        ("journalctl -p err", "Logs con nivel error o superior"),
        ("tail -f /var/log/syslog", "Sigue syslog en tiempo real"),
        ("tail -f /var/log/messages", "Sigue mensajes del sistema"),
        ("dmesg -w", "Sigue mensajes del kernel"),
        ("dmesg --level=err,warn", "Mensajes del kernel de error/warn"),
        ("iostat -x 1", "Estadísticas de I/O cada segundo"),
        ("iostat -c", "Estadísticas de CPU"),
        ("vmstat 1", "Estadísticas de memoria, CPU, I/O"),
        ("vmstat -s", "Resumen de estadísticas"),
        ("sar -u 1 5", "CPU cada 1s, 5 muestras"),
        ("sar -r", "Estadísticas de memoria"),
        ("sar -n DEV 1", "Tráfico de red por interfaz"),
        ("perf top", "Perfilado en tiempo real del sistema"),
        ("strace -p <PID>", "Rastrea syscalls de un proceso"),
        ("ltrace -p <PID>", "Rastrea llamadas a bibliotecas"),
        ("lsof -i", "Conexiones de red abiertas"),
    ],
    "Docker": [
        ("docker ps", "Lista contenedores en ejecución"),
        ("docker ps -a", "Lista todos los contenedores"),
        ("docker images", "Lista imágenes locales"),
        ("docker pull <image>", "Descarga una imagen"),
        ("docker push <image>", "Sube una imagen al registro"),
        ("docker run <image>", "Ejecuta un contenedor"),
        ("docker run -d <image>", "Ejecuta contenedor en segundo plano"),
        ("docker run --rm <image>", "Ejecuta y elimina al finalizar"),
        ("docker run -it <image> bash", "Ejecuta interactivo con bash"),
        ("docker run -p 8080:80 <image>", "Mapea puerto host:contenedor"),
        ("docker run -v /host:/container <image>", "Monta volumen bind"),
        ("docker start <container>", "Inicia contenedor detenido"),
        ("docker stop <container>", "Detiene un contenedor"),
        ("docker restart <container>", "Reinicia un contenedor"),
        ("docker kill <container>", "Mata un contenedor"),
        ("docker rm <container>", "Elimina un contenedor"),
        ("docker rm -f <container>", "Fuerza eliminación de contenedor"),
        ("docker rmi <image>", "Elimina una imagen"),
        ("docker rmi -f <image>", "Fuerza eliminación de imagen"),
        ("docker build -t <tag> .", "Construye imagen desde Dockerfile"),
        ("docker build --no-cache -t <tag> .", "Construye sin caché"),
        ("docker exec -it <container> bash", "Ejecuta bash en contenedor"),
        ("docker logs <container>", "Muestra logs del contenedor"),
        ("docker logs -f <container>", "Sigue logs en tiempo real"),
        ("docker inspect <container>", "Información detallada"),
        ("docker stats", "Estadísticas en tiempo real"),
        ("docker top <container>", "Procesos dentro del contenedor"),
        ("docker network ls", "Lista redes Docker"),
        ("docker network create <net>", "Crea una red"),
        ("docker network connect <net> <container>", "Conecta a red"),
        ("docker volume ls", "Lista volúmenes"),
        ("docker volume create <vol>", "Crea un volumen"),
        ("docker compose up", "Levanta servicios con docker-compose"),
        ("docker compose up -d", "Levanta servicios en segundo plano"),
        ("docker compose down", "Detiene y elimina servicios"),
        ("docker compose logs", "Logs de servicios compose"),
        ("docker system prune", "Limpia recursos no usados"),
        ("docker system df", "Uso de disco de Docker"),
    ],
    "Git": [
        ("git init", "Inicializa repositorio Git"),
        ("git clone <url>", "Clona un repositorio remoto"),
        ("git add <file>", "Añade archivo al stage"),
        ("git add .", "Añade todos los cambios al stage"),
        ("git add -p", "Añade cambios interactivamente por hunk"),
        ("git commit -m 'msg'", "Crea un commit con mensaje"),
        ("git commit --amend", "Modifica el último commit"),
        ("git status", "Estado del repositorio"),
        ("git log", "Historial de commits"),
        ("git log --oneline --graph", "Historial compacto con gráfico"),
        ("git diff", "Cambios sin stage"),
        ("git diff --staged", "Cambios en stage"),
        ("git diff <branch>..<branch>", "Diferencias entre ramas"),
        ("git branch", "Lista ramas locales"),
        ("git branch <name>", "Crea una nueva rama"),
        ("git branch -d <name>", "Elimina rama"),
        ("git checkout <branch>", "Cambia de rama"),
        ("git checkout -b <branch>", "Crea y cambia a nueva rama"),
        ("git switch <branch>", "Cambia de rama (moderno)"),
        ("git switch -c <branch>", "Crea y cambia a nueva rama"),
        ("git merge <branch>", "Fusiona rama en la actual"),
        ("git merge --no-ff <branch>", "Fusiona sin fast-forward"),
        ("git rebase <branch>", "Reubica commits sobre otra base"),
        ("git rebase -i HEAD~3", "Rebase interactivo últimos 3 commits"),
        ("git pull", "Trae y fusiona cambios remotos"),
        ("git pull --rebase", "Trae y reubica cambios locales"),
        ("git push", "Sube commits al remoto"),
        ("git push origin <branch>", "Sube rama específica"),
        ("git push --tags", "Sube etiquetas al remoto"),
        ("git remote -v", "Muestra repositorios remotos"),
        ("git remote add origin <url>", "Añade remoto"),
        ("git tag <name>", "Crea una etiqueta"),
        ("git stash", "Guarda cambios temporalmente"),
        ("git stash pop", "Recupera y elimina stash"),
        ("git reset HEAD <file>", "Quita archivo del stage"),
        ("git reset --hard HEAD~1", "Borra último commit y cambios"),
        ("git revert <commit>", "Revierte un commit creando nuevo commit"),
        ("git cherry-pick <commit>", "Aplica commit específico a la rama"),
    ],
    "UPS / Power": [
        ("upsc <ups>", "Consultar estado del UPS via NUT"),
        ("upsc <ups>@<host>", "Consultar UPS remoto via NUT"),
        ("upsc -l", "Listar UPS disponibles en NUT"),
        ("upscmd <ups> shutdown.return", "Apagar UPS y reiniciar cuando vuelva la línea"),
        ("upscmd <ups> test.battery.start.quick", "Iniciar test rápido de batería"),
        ("upscmd <ups> test.battery.start.deep", "Iniciar test profundo de batería"),
        ("upscmd -l <ups>", "Listar comandos disponibles para el UPS"),
        ("upsrw <ups>", "Leer/escribir variables del UPS"),
        ("upsmon -c stop", "Detener monitoreo de UPS"),
        ("upsd", "Servidor NUT (Network UPS Tools)"),
        ("nut-scanner", "Descubrir dispositivos UPS en la red"),
        ("apcaccess", "Estado del UPS APC local (via apcupsd)"),
        ("apcaccess -h <host>", "Estado del UPS APC remoto"),
        ("pwrstat -status", "Estado del UPS CyberPower"),
        ("pwrstat -pwroff", "Apagar salida del UPS CyberPower"),
        ("pwrstat -cs", "Configuración de CyberPower"),
        ("pwrstat -test", "Ejecutar test de batería CyberPower"),
    ],
    "Redes y Firewall nftables/iptables": [
        ("iptables -L -n -v", "Lista reglas iptables"),
        ("iptables -A INPUT -p tcp --dport 22 -j ACCEPT", "Permite SSH INPUT"),
        ("iptables -A INPUT -s <ip> -j DROP", "Bloquea IP en INPUT"),
        ("iptables -P INPUT DROP", "Política por defecto DROP en INPUT"),
        ("iptables -t nat -L -n", "Lista reglas NAT"),
        ("iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT", "Permite reenvío"),
        ("iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT", "Permite conexiones establecidas"),
        ("iptables-save > rules.v4", "Guarda reglas IPv4"),
        ("iptables-restore < rules.v4", "Restaura reglas IPv4"),
        ("nft list ruleset", "Lista todas las reglas nftables"),
        ("nft add table inet filter", "Crea tabla nftables"),
        ("nft add chain inet filter input '{type filter hook input priority 0;}'", "Crea cadena input"),
        ("nft add rule inet filter input tcp dport 22 accept", "Permite SSH"),
        ("nft add rule inet filter input ip saddr <ip> drop", "Bloquea IP"),
        ("nft -f <file>", "Carga reglas desde archivo"),
    ],
}
