WINDOWS_COMMANDS = {
    "Sistema y Configuración": [
        ("systeminfo", "Información detallada del sistema"),
        ("systeminfo | findstr /B /C:\"OS\"", "Muestra solo la versión del SO"),
        ("hostname", "Nombre del equipo"),
        ("winver", "Versión de Windows (GUI)"),
        ("ver", "Versión de Windows (CMD)"),
        ("msinfo32", "Información del sistema (GUI)"),
        ("dxdiag", "Diagnóstico de DirectX"),
        ("slmgr /dli", "Información de licencia de Windows"),
        ("slmgr /xpr", "Estado de activación de Windows"),
        ("slmgr /ipk <clave>", "Instala clave de producto"),
        ("shutdown /s /t 0", "Apaga el equipo inmediatamente"),
        ("shutdown /r /t 0", "Reinicia el equipo"),
        ("shutdown /l", "Cierra sesión"),
        ("shutdown /h", "Hiberna el equipo"),
        ("shutdown /a", "Cancela apagado programado"),
        ("powercfg /hibernate on/off", "Activa/desactiva hibernación"),
        ("powercfg /energy", "Informe de eficiencia energética"),
        ("powercfg /batteryreport", "Informe de batería"),
        ("wmic ups get name,status,batterylife,estimatedruntime", "Estado del UPS (Windows WMI)"),
        ("wmic ups where \"name='UPS'\" list full", "Todos los datos del UPS via WMI"),
        ("wmic /namespace:\\\\root\\wmi path BatteryDischarge get *", "Descarga de batería"),
        ("wmic /namespace:\\\\root\\wmi path BatteryStatus get *", "Estado de batería"),
        ("sfc /scannow", "Verifica y repara archivos del sistema"),
        ("chkdsk C: /f", "Verifica disco y corrige errores"),
        ("chkdsk C: /r", "Verifica y recupera sectores dañados"),
        ("dism /online /cleanup-image /restorehealth", "Repara imagen del sistema"),
        ("dism /online /cleanup-image /checkhealth", "Verifica estado de la imagen"),
        ("regedit", "Editor del registro (GUI)"),
        ("reg query <key>", "Consulta valor del registro"),
        ("reg add <key> /v <name> /t <type> /d <data>", "Añade valor al registro"),
        ("reg delete <key> /v <name>", "Elimina valor del registro"),
        ("msconfig", "Configuración del sistema (GUI)"),
        ("gpedit.msc", "Editor de directivas de grupo (GUI)"),
        ("control", "Panel de control (GUI)"),
        ("control system", "Propiedades del sistema (GUI)"),
        ("taskmgr", "Administrador de tareas (GUI)"),
        ("resmon", "Monitor de recursos (GUI)"),
        ("perfmon", "Monitor de rendimiento (GUI)"),
        ("services.msc", "Administrador de servicios (GUI)"),
        ("mmc", "Consola de administración (GUI)"),
        ("bcdedit /enum", "Configuración del arranque"),
        ("bcdedit /set {default} bootmenupolicy legacy", "Menú de arranque clásico"),
    ],
    "Red": [
        ("ipconfig", "Configuración IP básica"),
        ("ipconfig /all", "Configuración IP detallada"),
        ("ipconfig /release", "Libera dirección IP"),
        ("ipconfig /renew", "Renueva dirección IP"),
        ("ipconfig /flushdns", "Limpia caché DNS"),
        ("ipconfig /displaydns", "Muestra caché DNS"),
        ("ping <host>", "Prueba conectividad"),
        ("ping -t <host>", "Ping continuo"),
        ("ping -n 10 <host>", "Envía 10 paquetes"),
        ("tracert <host>", "Rastro de ruta"),
        ("pathping <host>", "Ruta con estadísticas de pérdida"),
        ("nslookup <domain>", "Consulta DNS"),
        ("nslookup -type=mx <domain>", "Registros MX"),
        ("netstat -an", "Conexiones y puertos"),
        ("netstat -b", "Conexiones con programas asociados"),
        ("netstat -n", "Direcciones y puertos numéricos"),
        ("netstat -an | findstr :80", "Filtra puerto 80"),
        ("route print", "Tabla de enrutamiento"),
        ("route -p add <red> mask <mask> <gw>", "Añade ruta persistente"),
        ("route delete <red>", "Elimina ruta"),
        ("arp -a", "Tabla ARP"),
        ("arp -d <ip>", "Elimina entrada ARP"),
        ("getmac", "Dirección MAC del equipo"),
        ("netsh interface ip show config", "Configuración de interfaces"),
        ("netsh interface ip set address <if> static <ip> <mask> <gw>", "IP estática"),
        ("netsh interface ip set dns <if> static <dns>", "DNS estático"),
        ("netsh interface ip add dns <if> <dns> index=2", "DNS secundario"),
        ("netsh advfirewall show allprofiles", "Estado del firewall"),
        ("netsh advfirewall set allprofiles state on/off", "Activa/desactiva firewall"),
        ("netsh advfirewall firewall add rule name=\"<name>\" dir=in action=allow protocol=tcp localport=<port>", "Permite puerto"),
        ("netsh wlan show profiles", "Perfiles WiFi guardados"),
        ("netsh wlan show profile <name> key=clear", "Muestra contraseña WiFi"),
        ("netsh wlan connect name=<ssid>", "Conecta a WiFi"),
        ("telnet <host> <port>", "Prueba puerto TCP"),
        ("ssh <user>@<host>", "Conexión SSH (OpenSSH)"),
        ("net use Z: \\\\<server>\\<share>", "Asigna unidad de red"),
        ("net use Z: /delete", "Elimina unidad de red mapeada"),
        ("net view", "Lista equipos de la red"),
        ("net share", "Recursos compartidos locales"),
        ("net start/stop <service>", "Inicia/detiene servicio"),
        ("nbtstat -A <ip>", "Nombre NetBIOS de la IP"),
        ("nbtstat -n", "Tabla de nombres NetBIOS locales"),
        ("nbtstat -c", "Caché de nombres NetBIOS remotos"),
        ("netstat -e -s", "Estadísticas de red detalladas"),
        ("netstat -r", "Tabla de rutas (como route print)"),
        ("netstat -o", "Conexiones con PID del proceso"),
        ("netstat -p tcp", "Conexiones TCP únicamente"),
        ("netstat -s -p tcp", "Estadísticas TCP"),
        ("netsh interface ip show addresses", "Direcciones IP detalladas"),
        ("netsh interface ip show subinterfaces", "Estadísticas por interfaz"),
        ("netsh interface ip show dnsservers", "Servidores DNS configurados"),
        ("netsh interface ip show wins", "Servidores WINS"),
        ("netsh interface ipv6 show addresses", "Direcciones IPv6"),
        ("netsh interface ipv6 show route", "Rutas IPv6"),
        ("netsh interface portproxy show all", "Reenvío de puertos (portproxy)"),
        ("netsh trace start capture=yes", "Inicia captura de paquetes"),
        ("netsh trace stop", "Detiene captura de paquetes"),
        ("netsh http show servicestate", "Estado del servicio HTTP"),
        ("netsh wlan show drivers", "Controladores WiFi y características"),
        ("netsh wlan show interfaces", "Interfaces WiFi activas"),
        ("netsh wlan show networks mode=bssid", "Redes WiFi con BSSID y señal"),
        ("netsh wlan disconnect", "Desconecta WiFi"),
        ("netsh wlan delete profile <name>", "Elimina perfil WiFi"),
        ("netsh lan show profiles", "Perfiles de red cableada"),
        ("netsh firewall show state", "Estado del firewall (legacy)"),
        ("netsh routing ip show rip", "Rutas RIP"),
        ("netsh routing ip show nat", "Configuración NAT"),
        ("Get-NetIPConfiguration", "Configuración IP completa (PowerShell)"),
        ("Get-NetIPAddress", "Direcciones IP (PowerShell)"),
        ("Get-NetRoute", "Tabla de rutas (PowerShell)"),
        ("Get-NetNeighbor", "Tabla ARP/NDP (PowerShell)"),
        ("Get-NetAdapter", "Adaptadores de red (PowerShell)"),
        ("Get-NetAdapterStatistics", "Estadísticas de adaptador (PowerShell)"),
        ("Get-NetTCPConnection", "Conexiones TCP activas (PowerShell)"),
        ("Get-NetUDPEndpoint", "Puertos UDP en escucha (PowerShell)"),
        ("Get-DnsClientCache", "Caché DNS (PowerShell)"),
        ("Get-DnsClientServerAddress", "Servidores DNS (PowerShell)"),
        ("Resolve-DnsName <domain>", "Resolución DNS avanzada (PowerShell)"),
        ("Test-NetConnection <host> -Port <port>", "Prueba conectividad y puerto (PowerShell)"),
        ("Test-NetConnection <host> -TraceRoute", "Traceroute con PowerShell"),
        ("Get-WmiObject Win32_NetworkAdapter", "Adaptadores de red (WMI)"),
        ("Get-WmiObject Win32_NetworkAdapterConfiguration", "Configuración de red (WMI)"),
        ("wmic nic get name,speed,macaddress", "NICs y velocidad"),
        ("wmic nicconfig get ipaddress,defaultipgateway", "IP y gateway"),
        ("winsock reset", "Restablece catálogo Winsock"),
        ("netsh winsock reset catalog", "Reset Winsock (alternativa)"),
        ("netsh int ip reset", "Reset pila TCP/IP"),
        ("netsh int ipv6 reset", "Reset IPv6"),
        ("ipconfig /registerdns", "Refresca registro DNS dinámico"),
        ("ipconfig /setclassid <adapter> <id>", "Asigna ID de clase DHCP"),
        ("route print -4", "Rutas IPv4"),
        ("route print -6", "Rutas IPv6"),
        ("route change <dest> mask <mask> <gw>", "Cambia ruta existente"),
        ("route -p add ::/0 <ipv6gw>", "Ruta predeterminada IPv6 persistente"),
        ("arp -s <ip> <mac>", "Añade entrada ARP estática"),
        ("arp -g", "Tabla ARP (mismo que -a)"),
        ("getmac /s <host> /u <user>", "MAC de equipo remoto"),
        ("tracert -d <host>", "Traceroute sin resolución DNS"),
        ("tracert -6 <host>", "Traceroute IPv6"),
        ("pathping -n <host>", "Pathping sin resolución DNS"),
        ("ping -6 <host>", "Ping IPv6"),
        ("ping -l 1500 <host>", "Ping con tamaño de paquete"),
        ("ping -f <host>", "Ping con flag Don't Fragment"),
        ("nslookup -type=any <domain>", "Todos los registros DNS"),
        ("nslookup <domain> <dns_server>", "Consulta a DNS específico"),
        ("nslookup -type=srv <domain>", "Registros SRV"),
        ("nslookup -type=txt <domain>", "Registros TXT"),
        ("nslookup -type=aaaa <domain>", "Registros AAAA (IPv6)"),
        ("nslookup -q=ns <domain>", "Servidores DNS autoritativos"),
    ],
    "Discos y Almacenamiento": [
        ("wmic diskdrive get model,size,status", "Información de discos físicos"),
        ("wmic logicaldisk get name,size,freespace", "Información de particiones"),
        ("fsutil volume diskfree C:", "Espacio libre en C:"),
        ("fsutil fsinfo drives", "Lista unidades disponibles"),
        ("diskpart", "Administrador de particiones (interactivo)"),
        ("diskpart /s <script>", "Ejecuta script de diskpart"),
        ("list disk", "Dentro de diskpart: lista discos"),
        ("select disk <n>", "Dentro de diskpart: selecciona disco"),
        ("clean", "Dentro de diskpart: limpia disco"),
        ("create partition primary size=<mb>", "Dentro de diskpart: crea partición"),
        ("format fs=ntfs quick", "Dentro de diskpart: formatea como NTFS"),
        ("assign letter=<letra>", "Dentro de diskpart: asigna letra"),
        ("vssadmin list shadows", "Lista instantáneas (shadow copies)"),
        ("vssadmin create shadow /for=C:", "Crea instantánea de volumen"),
        ("diskmgmt.msc", "Administración de discos (GUI)"),
        ("mountvol", "Lista puntos de montaje"),
        ("mountvol <ruta> /l", "UUID del volumen"),
        ("chkdsk D: /f /r", "Verifica disco con reparación"),
        ("defrag C: /U /V", "Desfragmenta disco con detalle"),
        ("defrag C: /O", "Optimiza almacenamiento"),
        ("cleanmgr", "Liberador de espacio en disco (GUI)"),
        ("cleanmgr /sagerun:1", "Liberador de espacio automático"),
        ("compmgmt.msc", "Administración de equipos (GUI)"),
        ("wmic partition get name,size,type", "Particiones y tipos"),
        ("wmic volume get name,label,capacity,freespace", "Volúmenes y espacio"),
    ],
    "Active Directory": [
        ("dsquery user -name <pattern>", "Busca usuarios en AD"),
        ("dsquery computer -name <pattern>", "Busca equipos en AD"),
        ("dsquery group -name <pattern>", "Busca grupos en AD"),
        ("dsquery * <dn> -scope base", "Atributos de un objeto"),
        ("dsget user <dn> -display", "Propiedades de usuario"),
        ("dsadd user <dn> -pwd <pass>", "Crea usuario en AD"),
        ("dsrm <dn>", "Elimina objeto de AD"),
        ("dsmove <dn> -newparent <parent_dn>", "Mueve objeto a otra OU"),
        ("net user <user> /domain", "Información de usuario del dominio"),
        ("net group <group> /domain", "Información de grupo del dominio"),
        ("net localgroup", "Grupos locales"),
        ("net localgroup Administrators <user> /add", "Añade usuario a administradores"),
        ("whoami /user", "Usuario actual con SID"),
        ("whoami /groups", "Grupos del usuario actual"),
        ("whoami /priv", "Privilegios del usuario"),
        ("gpupdate /target:computer /force", "Actualiza directivas de grupo"),
        ("gpresult /r", "Directivas aplicadas (resumen)"),
        ("gpresult /z", "Directivas aplicadas (detalle)"),
        ("nltest /dsgetdc:<domain>", "Controlador de dominio"),
        ("nltest /dclist:<domain>", "Lista de controladores de dominio"),
        ("repadmin /showrepl", "Estado de replicación"),
        ("repadmin /replsummary", "Resumen de replicación"),
        ("dcdiag /v /c", "Diagnóstico de controlador de dominio"),
        ("csvde -r <filtro> -f <archivo.csv>", "Exporta objetos a CSV"),
    ],
    "PowerShell": [
        ("Get-Process", "Lista procesos en ejecución"),
        ("Get-Process -Name <name> | Stop-Process", "Detiene proceso por nombre"),
        ("Get-Service", "Lista servicios"),
        ("Start-Service <name>", "Inicia servicio"),
        ("Stop-Service <name>", "Detiene servicio"),
        ("Get-EventLog System -Newest 10", "Últimos 10 eventos del sistema"),
        ("Get-EventLog Application -EntryType Error", "Errores de aplicación"),
        ("Get-ChildItem -Path C:\\ -Recurse -Filter *.log", "Busca archivos .log recursivamente"),
        ("Get-ChildItem -Recurse -Force | Where-Object { \$_.Length -gt 100MB }", "Archivos mayores a 100MB"),
        ("Select-String -Path <file> -Pattern <text>", "Busca texto en archivos"),
        ("Get-Content <file> -Tail 50", "Últimas 50 líneas de un archivo"),
        ("Measure-Command { <cmd> }", "Mide tiempo de ejecución"),
        ("Test-Connection <host> -Count 1", "Ping a un host"),
        ("Test-NetConnection <host> -Port <port>", "Prueba conectividad y puerto"),
        ("Invoke-WebRequest -Uri <url>", "Descarga contenido web"),
        ("Invoke-WebRequest -Uri <url> -OutFile <file>", "Descarga archivo"),
        ("Get-Command -Module ActiveDirectory", "Comandos del módulo AD"),
        ("Get-WMIObject Win32_BIOS", "Información BIOS"),
        ("Get-WMIObject Win32_ComputerSystem", "Información del equipo"),
        ("Get-WMIObject Win32_LogicalDisk -Filter 'DriveType=3'", "Discos locales"),
        ("New-Item -Path <path> -ItemType Directory", "Crea directorio"),
        ("Remove-Item -Path <path> -Recurse -Force", "Elimina archivo/directorio"),
        ("Copy-Item -Path <src> -Destination <dst> -Recurse", "Copia archivos"),
        ("Move-Item -Path <src> -Destination <dst>", "Mueve archivos"),
        ("Rename-Item -Path <old> -NewName <new>", "Renombra archivo"),
        ("Set-Content -Path <file> -Value <content>", "Escribe contenido en archivo"),
        ("Export-Csv -Path <file> -NoTypeInformation", "Exporta a CSV"),
        ("ConvertTo-Json", "Convierte objeto a JSON"),
        ("Start-Transcript -Path <file>", "Inicia registro de sesión"),
        ("Stop-Transcript", "Detiene registro de sesión"),
        ("Set-ExecutionPolicy RemoteSigned -Scope CurrentUser", "Política de ejecución"),
        ("Get-History", "Historial de comandos de la sesión"),
        ("Get-NetIPAddress", "Direcciones IP del sistema"),
        ("Get-NetAdapter", "Adaptadores de red"),
        ("Set-DnsClientServerAddress -InterfaceIndex <n> -ServerAddresses <dns>", "Configura DNS"),
        ("New-SmbShare -Name <name> -Path <path> -FullAccess <user>", "Crea recurso compartido"),
    ],
    "Diagnóstico": [
        ("perfmon /rel", "Informe de fiabilidad"),
        ("eventvwr.msc", "Visor de eventos (GUI)"),
        ("wevtutil el", "Lista logs de eventos"),
        ("wevtutil qe <log> /c:10 /rd:true /f:text", "Últimos 10 eventos de un log"),
        ("get-winevent -logname system -maxevents 10", "Últimos 10 eventos del sistema"),
        ("msra /offerra", "Asistencia remota"),
        ("mstsc", "Conexión a escritorio remoto (GUI)"),
        ("mstsc /v:<ip>", "RDP a una IP"),
        ("mstsc /admin", "RDP a sesión de administración"),
        ("wpr -start cpu", "Grabación de rendimiento de CPU"),
        ("wpr -stop <file>.etl", "Detiene grabación de rendimiento"),
        ("xperf -on PROC_THREAD+LOADER -stackwalk profile", "Trazado avanzado"),
        ("xperf -d <file>.etl", "Detiene y guarda trazado"),
        ("odbcad32", "Administrador de orígenes de datos ODBC"),
        ("drwtsn32", "Watson (depurador de errores)"),
        ("sigverif", "Verificador de firmas de archivos"),
        ("verifier", "Administrador de verificador de controladores"),
        ("logman start <name> -p <provider> -o <file>", "Inicia recolección de datos"),
        ("logman stop <name>", "Detiene recolección de datos"),
        ("logman query <name>", "Consulta estado de recolección"),
        ("tlist", "Lista procesos con TIDs"),
        ("dumpel /l system /f <file>", "Exporta log del sistema"),
    ],
    "Procesos y Servicios": [
        ("tasklist", "Lista procesos en ejecución"),
        ("tasklist /v", "Lista procesos con detalle"),
        ("tasklist /S <host> /U <user>", "Procesos de equipo remoto"),
        ("tasklist /M <dll>", "Procesos que usan una DLL"),
        ("taskkill /PID <pid>", "Mata proceso por PID"),
        ("taskkill /IM <name> /F", "Mata proceso por nombre forzadamente"),
        ("taskkill /F /PID <pid> /T", "Mata proceso e hijos"),
        ("sc query", "Lista servicios con estado"),
        ("sc query <name>", "Estado de un servicio específico"),
        ("sc start <name>", "Inicia servicio"),
        ("sc stop <name>", "Detiene servicio"),
        ("sc delete <name>", "Elimina servicio"),
        ("sc config <name> start= auto", "Servicio con inicio automático"),
        ("sc config <name> start= disabled", "Deshabilita servicio"),
        ("sc failure <name> reset= 86400 actions= restart/5000", "Recuperación por fallo"),
        ("wmic service where name='<name>' get *", "Detalle de servicio"),
        ("wmic process where processid=<pid> get *", "Detalle de proceso"),
        ("wmic process call create '<cmd>'", "Ejecuta proceso en segundo plano"),
        ("wmic process delete where processid=<pid>", "Termina proceso"),
        ("net start/stop <service>", "Inicia/detiene servicio (legacy)"),
        ("start /b <cmd>", "Ejecuta comando en segundo plano"),
        ("cmd /c start /min <cmd>", "Ejecuta minimizado"),
        ("at <time> <cmd>", "Programa tarea (obsoleto)"),
        ("schtasks /create /tn <name> /tr <cmd> /sc daily /st <time>", "Crea tarea programada"),
        ("schtasks /query /v /fo list", "Lista tareas programadas"),
        ("schtasks /run /tn <name>", "Ejecuta tarea"),
        ("schtasks /end /tn <name>", "Detiene tarea"),
        ("schtasks /delete /tn <name> /f", "Elimina tarea"),
    ],
    "Scripting (CMD)": [
        ("@echo off", "Desactiva eco de comandos"),
        ("echo <text>", "Muestra texto en pantalla"),
        ("echo.> <file>", "Crea archivo vacío"),
        ("echo %variable%", "Muestra variable"),
        ("set <var>=<value>", "Asigna variable"),
        ("set /p <var>=<prompt>", "Solicita entrada al usuario"),
        ("set /a <var>=<expr>", "Operación aritmética"),
        ("setlocal enabledelayedexpansion", "Habilita expansión retardada"),
        ("endlocal", "Finaliza ámbito local de variables"),
        ("if \"%a%\"==\"b\" (<cmd>)", "Condicional simple"),
        ("if exist <file> (<cmd>)", "Condicional por existencia"),
        ("if errorlevel 1 (<cmd>)", "Condicional por código de error"),
        ("for %%i in (*.txt) do <cmd>", "Bucle sobre archivos"),
        ("for /l %%i in (1,1,10) do <cmd>", "Bucle numérico"),
        ("for /f \"tokens=*\" %%i in (<file>) do <cmd>", "Bucle leyendo archivo"),
        ("for /f \"usebackq\" %%i in (`<cmd>`) do <cmd>", "Bucle sobre salida de comando"),
        ("goto :label", "Salto a etiqueta"),
        (":label", "Define etiqueta"),
        ("call :subroutine", "Llama a subrutina"),
        ("exit /b <code>", "Sale con código de error"),
        ("shift", "Desplaza parámetros"),
        ("%1 %2 %*", "Parámetros posicionales"),
        ("%cd%", "Directorio actual"),
        ("%date% / %time%", "Fecha y hora del sistema"),
        ("%random%", "Número aleatorio 0-32767"),
        ("%errorlevel%", "Código de retorno del último comando"),
        ("%processor_architecture%", "Arquitectura del procesador"),
        ("> < >> 2>&1", "Redirección de salida y errores"),
        ("|", "Tubería (pipe) entre comandos"),
        ("&", "Ejecuta comandos secuencialmente"),
        ("&&", "Ejecuta siguiente si el anterior tuvo éxito"),
        ("||", "Ejecuta siguiente si el anterior falló"),
        ("type <file>", "Muestra contenido de archivo"),
        ("more < <file>", "Paginación de archivo"),
        ("copy <src> <dst>", "Copia archivos"),
        ("xcopy <src> <dst> /E /I", "Copia directorios"),
        ("robocopy <src> <dst> /E /COPY:DAT /R:3 /W:5", "Copia avanzada con reintentos"),
        ("move <src> <dst>", "Mueve archivos"),
        ("del /f /q <file>", "Elimina archivo forzadamente"),
        ("rmdir /s /q <dir>", "Elimina directorio recursivamente"),
        ("ren <old> <new>", "Renombra archivo"),
        ("mkdir <dir>", "Crea directorio"),
        ("attrib +h +s <file>", "Archivo oculto y de sistema"),
        ("assoc .txt=txtfile", "Asocia extensión a tipo"),
        ("ftype txtfile=%SystemRoot%\notepad.exe %1", "Tipo de archivo asociado"),
        ("cipher /w:C:", "Sobrescribe espacio libre en disco"),
        ("fc <f1> <f2>", "Compara archivos"),
        ("comp <f1> <f2>", "Compara archivos binarios"),
        ("prompt $P$G", "Personaliza el prompt"),
        ("color 0a", "Color de consola (fondo negro, texto verde)"),
        ("title <text>", "Título de la ventana"),
    ],
}
