MIKROTIK_COMMANDS = {
    "Básicos": [
        ("/system resource print", "Mostrar recursos del sistema"),
        ("/system identity set name=MIROUTER", "Cambiar nombre del router"),
        ("/system clock print", "Mostrar fecha/hora"),
        ("/system clock set date=Jan/01/2025 time=12:00:00", "Configurar fecha/hora"),
        ("/system reboot", "Reiniciar el router"),
        ("/system shutdown", "Apagar el router"),
        ("/system backup save name=backup.backup", "Guardar backup del sistema"),
        ("/system backup load name=backup.backup", "Restaurar backup"),
        ("/export file=config.rsc", "Exportar configuración a archivo"),
        ("/import file=config.rsc", "Importar configuración desde archivo"),
        ("/password", "Cambiar contraseña del admin"),
        ("/user add name=admin2 group=full password=123", "Agregar usuario"),
        ("/user print", "Listar usuarios"),
    ],
    "Interfaces": [
        ("/interface print", "Listar todas las interfaces"),
        ("/interface ethernet print", "Listar interfaces ethernet"),
        ("/interface ethernet set ether1 name=WAN", "Renombrar interfaz"),
        ("/interface ethernet set ether2 name=LAN", "Renombrar interfaz"),
        ("/interface wireless print", "Listar interfaces inalámbricas"),
        ("/interface wireless set wlan1 band=2ghz-b/g/n channel-width=20", "Configurar WiFi"),
        ("/interface wireless set wlan1 ssid=MiRed mode=ap-bridge", "Configurar SSID"),
        ("/interface wireless security-profiles set default authentication-types=wpa2-psk", "Seguridad WiFi"),
        ("/interface wireless security-profiles set default wpa2-pre-shared-key=MIPASS", "Contraseña WiFi"),
        ("/interface wireless enable wlan1", "Activar WiFi"),
        ("/interface bridge add name=bridge-local", "Crear bridge"),
        ("/interface bridge port add bridge=bridge-local interface=ether2", "Agregar puerto a bridge"),
        ("/interface bonding add name=bond1 mode=802.3ad slaves=ether3,ether4", "Creación de bonding LACP"),
        ("/interface vlan add name=vlan10 vlan-id=10 interface=bridge-local", "Crear VLAN"),
        ("/interface list add name=WAN", "Crear lista de interfaces"),
        ("/interface list member add list=WAN interface=ether1", "Agregar a lista"),
    ],
    "IP / Direcciones": [
        ("/ip address print", "Listar direcciones IP"),
        ("/ip address add address=192.168.1.1/24 interface=ether2", "Asignar IP a interfaz"),
        ("/ip address add address=10.0.0.1/30 interface=ether1", "Asignar IP WAN"),
        ("/ip route print", "Mostrar tabla de enrutamiento"),
        ("/ip route add dst-address=0.0.0.0/0 gateway=10.0.0.2", "Ruta por defecto"),
        ("/ip route add dst-address=10.0.0.0/8 gateway=192.168.1.254", "Ruta estática"),
        ("/ip dns set servers=8.8.8.8,8.8.4.4 allow-remote-requests=yes", "Configurar DNS"),
        ("/ip dns cache print", "Mostrar caché DNS"),
        ("/ip neighbor print", "Mostrar vecinos descubiertos"),
    ],
    "Firewall": [
        ("/ip firewall filter print", "Listar reglas de firewall"),
        ("/ip firewall filter add chain=input protocol=tcp dst-port=22 action=accept", "Permitir SSH"),
        ("/ip firewall filter add chain=input protocol=icmp action=accept", "Permitir ICMP"),
        ("/ip firewall filter add chain=input connection-state=established,related action=accept", "Permitir conexiones establecidas"),
        ("/ip firewall filter add chain=input action=drop", "Bloquear todo lo demás (input)"),
        ("/ip firewall filter add chain=forward action=drop", "Bloquear forward por defecto"),
        ("/ip firewall filter add chain=forward connection-state=established,related action=accept", "Permitir conexiones establecidas en forward"),
        ("/ip firewall nat print", "Listar reglas NAT"),
        ("/ip firewall nat add chain=srcnat out-interface=ether1 action=masquerade", "Masquerade (NAT dinámico)"),
        ("/ip firewall nat add chain=dstnat dst-address=10.0.0.1 protocol=tcp dst-port=80 action=dst-nat to-addresses=192.168.1.10 to-ports=80", "Redirección de puertos"),
        ("/ip firewall nat add chain=dstnat dst-address=10.0.0.1 protocol=tcp dst-port=3389 action=dst-nat to-addresses=192.168.1.20 to-ports=3389", "Redirección RDP"),
        ("/ip firewall mangle print", "Listar reglas mangle"),
        ("/ip firewall address-list add list=bloqueados address=10.0.0.100", "Lista de direcciones"),
        ("/ip firewall filter add chain=input src-address-list=bloqueados action=drop", "Bloquear por address-list"),
    ],
    "DHCP": [
        ("/ip dhcp-server print", "Listar servidores DHCP"),
        ("/ip dhcp-server setup", "Asistente de configuración DHCP"),
        ("/ip dhcp-server add name=dhcp1 interface=bridge-local address-pool=pool1 lease-time=10m", "Crear servidor DHCP"),
        ("/ip pool add name=pool1 ranges=192.168.1.100-192.168.1.200", "Pool de direcciones"),
        ("/ip dhcp-server network add address=192.168.1.0/24 gateway=192.168.1.1 dns-server=8.8.8.8", "Red DHCP"),
        ("/ip dhcp-server lease print", "Listar concesiones activas"),
        ("/ip dhcp-server lease make-static [find]", "Hacer estática una concesión"),
        ("/ip dhcp-client add interface=ether1 disabled=no", "Cliente DHCP en WAN"),
    ],
    "Wireless": [
        ("/interface wireless set wlan1 band=5ghz-a/n/ac", "Configurar banda 5GHz"),
        ("/interface wireless set wlan1 channel-width=20/40/80mhz", "Ancho de canal"),
        ("/interface wireless set wlan1 frequency=5180", "Frecuencia específica"),
        ("/interface wireless set wlan1 country=Spain", "País (regulación)"),
        ("/interface wireless set wlan1 antenna-gain=3", "Ganancia de antena"),
        ("/interface wireless set wlan1 tx-power=20", "Potencia de transmisión"),
        ("/interface wireless set wlan1 wireless-protocol=802.11", "Protocolo inalámbrico"),
        ("/interface wireless set wlan1 mode=bridge", "Modo bridge inalámbrico"),
        ("/interface wireless set wlan1 mode=station-bridge", "Modo estación"),
        ("/interface wireless registration-table print", "Clientes WiFi conectados"),
        ("/interface wireless scan wlan1", "Escanear redes WiFi"),
        ("/interface wireless snooper", "Sniffer de paquetes WiFi"),
    ],
    "VPN": [
        ("/interface ovpn-server server set enabled=yes", "Activar servidor OpenVPN"),
        ("/interface ovpn-server server set port=1194", "Puerto OpenVPN"),
        ("/interface ovpn-server server set auth=sha256,sha512", "Autenticación"),
        ("/interface ovpn-server server set cipher=aes256", "Cifrado"),
        ("/ppp secret add name=cliente1 password=pass123 service=ovpn", "Crear usuario VPN"),
        ("/interface ovpn-client add name=ovpn-client1 connect-to=10.0.0.1 user=cliente1 password=pass123", "Cliente OpenVPN"),
        ("/ip ipsec policy print", "Políticas IPsec"),
        ("/ip ipsec peer add address=10.0.0.1/32 secret=MIPASS", "Peer IPsec"),
        ("/ip ipsec proposal set default enc-algorithms=aes-256-cbc", "Algoritmo IPsec"),
        ("/ip ipsec policy add src-address=10.0.0.0/24 dst-address=10.0.1.0/24 protocol=all proposal=default", "Policy IPsec"),
        ("/interface l2tp-server server set enabled=yes", "Servidor L2TP"),
        ("/interface l2tp-server server set use-ipsec=yes", "L2TP/IPsec"),
        ("/ppp profile add name=L2TP-Profile local-address=10.0.0.1 remote-address=10.0.0.100-10.0.0.200", "Perfil L2TP"),
    ],
    "Queues (QoS)": [
        ("/queue tree print", "Listar colas tree"),
        ("/queue simple print", "Listar colas simples"),
        ("/queue simple add name=CLIENTE1 target=192.168.1.10/32 max-limit=10M/10M", "Cola simple con límite"),
        ("/queue simple add name=CLIENTE2 target=192.168.1.20/32 max-limit=20M/5M", "Cola asimétrica"),
        ("/queue tree add name=DOWNLOAD parent=bridge-local max-limit=100M", "Cola tree"),
        ("/queue tree add name=UPLOAD parent=ether1 max-limit=50M", "Cola tree upload"),
        ("/queue type add name=PCQ-DOWN kind=pcq pcq-classifier=dst-address", "Tipo PCQ download"),
        ("/queue type add name=PCQ-UP kind=pcq pcq-classifier=src-address", "Tipo PCQ upload"),
    ],
    "Diagnóstico": [
        ("/ping 8.8.8.8", "Ping"),
        ("/tool traceroute 8.8.8.8", "Traceroute"),
        ("/tool bandwidth-test address=10.0.0.2 direction=both", "Test de ancho de banda"),
        ("/tool bandwidth-test address=10.0.0.2 protocol=udp direction=both user-size=1500", "Test con tamaño específico"),
        ("/tool sniffer quick interface=ether1", "Sniffer rápido de paquetes"),
        ("/tool sniffer start", "Iniciar sniffer"),
        ("/tool sniffer stop", "Detener sniffer"),
        ("/tool torch interface=ether1", "Monitor de tráfico en tiempo real"),
        ("/tool netwatch add host=8.8.8.8 interval=30s", "Monitoreo de host"),
        ("/tool email send to=admin@dominio.com subject=Alerta body=Texto", "Enviar email desde RouterOS"),
        ("/log print where topics=critical", "Ver logs críticos"),
        ("/log print where topics=warning", "Ver logs de advertencia"),
    ],
    "Routing": [
        ("/routing ospf instance print", "Instancias OSPF"),
        ("/routing ospf instance add name=ospf1 router-id=1.1.1.1", "Crear instancia OSPF"),
        ("/routing ospf network add network=192.168.1.0/24 area=backbone", "Red OSPF"),
        ("/routing bgp instance print", "Instancias BGP"),
        ("/routing bgp instance set default as=65000", "AS BGP"),
        ("/routing bgp peer add name=PEER1 remote-address=10.0.0.2 remote-as=65001", "Peer BGP"),
        ("/routing filter add chain=bgp-in rule=\"if dst-len > 24 { reject }\"", "Filtro BGP"),
    ],
    "CAPsMAN": [
        ("/caps-man manager set enabled=yes", "Activar CAPsMAN"),
        ("/caps-man manager interface add interface=bridge-local", "Interfaz CAPsMAN"),
        ("/caps-man datapath add name=datapath1 bridge=bridge-local", "Datapath"),
        ("/caps-man security add name=sec1 authentication-types=wpa2-psk passphrase=MIPASS", "Seguridad"),
        ("/caps-man configuration add name=cfg1 country=Spain datapath=datapath1 security=sec1", "Configuración"),
    ],
    "Hotspot": [
        ("/ip hotspot setup", "Asistente de hotspot"),
        ("/ip hotspot profile set [find] html-directory=hotspot", "Personalizar página de login"),
        ("/ip hotspot user add name=usuario1 password=pass123", "Crear usuario hotspot"),
        ("/ip hotspot active print", "Usuarios activos"),
        ("/ip hotspot active remove [find]", "Desconectar usuario"),
    ],
}
