CONSOLE_COMMANDS = {
    "Linux": {
        "Archivos": [
            ("ls -la", "Listar archivos con detalles"),
            ("ls -lh", "Listar con tamaños legibles"),
            ("ls -lt", "Listar ordenado por fecha"),
            ("ls -ltr", "Listar ordenado por fecha inverso"),
            ("pwd", "Directorio actual"),
            ("cd /ruta", "Cambiar directorio"),
            ("mkdir directorio", "Crear directorio"),
            ("mkdir -p a/b/c", "Crear directorios anidados"),
            ("rmdir directorio", "Eliminar directorio vacío"),
            ("rm archivo", "Eliminar archivo"),
            ("rm -rf directorio", "Eliminar directorio recursivo"),
            ("cp origen destino", "Copiar archivo"),
            ("cp -r origen destino", "Copiar directorio"),
            ("mv origen destino", "Mover/renombrar"),
            ("touch archivo", "Crear archivo vacío"),
            ("cat archivo", "Ver contenido"),
            ("less archivo", "Ver con paginación"),
            ("head -n 20 archivo", "Primeras 20 líneas"),
            ("tail -n 20 archivo", "Últimas 20 líneas"),
            ("tail -f archivo", "Seguir archivo"),
            ("wc -l archivo", "Contar líneas"),
            ("du -sh directorio", "Tamaño del directorio"),
            ("df -h", "Espacio en disco"),
            ("find / -name archivo", "Buscar archivo"),
            ("locate archivo", "Buscar en BD"),
            ("which comando", "Ruta del comando"),
            ("file archivo", "Tipo de archivo"),
            ("ln -s origen enlace", "Enlace simbólico"),
            ("chmod 755 archivo", "Permisos rwxr-xr-x"),
            ("chown user:group archivo", "Cambiar propietario"),
        ],
        "Procesos": [
            ("ps aux", "Todos los procesos"),
            ("top", "Monitor procesos"),
            ("htop", "Monitor mejorado"),
            ("kill PID", "Terminar proceso"),
            ("kill -9 PID", "Forzar terminación"),
            ("killall nombre", "Matar por nombre"),
            ("pgrep nombre", "Buscar PID"),
            ("nohup cmd &", "Ejecutar en background"),
            ("jobs", "Trabajos en bg"),
            ("fg %1", "Traer a foreground"),
            ("crontab -e", "Editar cron"),
            ("crontab -l", "Listar cron"),
            ("systemctl start svc", "Iniciar servicio"),
            ("systemctl stop svc", "Detener servicio"),
            ("systemctl restart svc", "Reiniciar servicio"),
            ("systemctl enable svc", "Habilitar en inicio"),
            ("systemctl status svc", "Estado del servicio"),
            ("journalctl -u svc", "Logs del servicio"),
            ("journalctl -f", "Seguir logs"),
            ("uptime", "Tiempo activo"),
            ("lsof -i :80", "Procesos en puerto 80"),
        ],
        "Red": [
            ("ip a", "Direcciones IP"),
            ("ip link show", "Interfaces"),
            ("ip route show", "Tabla de rutas"),
            ("ip neigh show", "Tabla ARP"),
            ("ip addr add 10.0.0.1/24 dev eth0", "Agregar IP"),
            ("ip link set eth0 up", "Activar interfaz"),
            ("ip link set eth0 down", "Desactivar interfaz"),
            ("ping -c 4 8.8.8.8", "Ping a internet"),
            ("ping -c 4 google.com", "Ping a dominio"),
            ("traceroute 8.8.8.8", "Trazar ruta"),
            ("mtr 8.8.8.8", "Traceroute + ping"),
            ("ss -tuln", "Puertos abiertos"),
            ("ss -tup", "Conexiones activas"),
            ("netstat -rn", "Tabla de rutas"),
            ("nmap -sT 192.168.1.1", "Escaneo básico"),
            ("nmap -sP 192.168.1.0/24", "Ping sweep"),
            ("nmap -sV 192.168.1.1", "Versiones servicios"),
            ("nmap -O 192.168.1.1", "Detección SO"),
            ("tcpdump -i eth0", "Capturar paquetes"),
            ("tcpdump -i eth0 port 80", "Capturar HTTP"),
            ("tcpdump -w captura.pcap", "Guardar captura"),
            ("wget http://url/archivo", "Descargar archivo"),
            ("curl http://api.com", "HTTP GET"),
            ("curl -X POST -d 'data' http://api.com", "HTTP POST"),
            ("curl -I https://ejemplo.com", "Solo headers"),
            ("dig dominio.com", "Consulta DNS"),
            ("nslookup dominio.com", "Consulta DNS"),
            ("host dominio.com", "Resolución DNS"),
            ("whois dominio.com", "Información WHOIS"),
            ("hostname", "Nombre del host"),
            ("hostname -I", "IPs locales"),
            ("ethtool eth0", "Info NIC"),
            ("iwlist wlan0 scan", "Escanear redes WiFi"),
        ],
        "Discos": [
            ("fdisk -l", "Listar discos"),
            ("fdisk /dev/sda", "Particionar"),
            ("mkfs.ext4 /dev/sda1", "Formatear ext4"),
            ("mount /dev/sda1 /mnt", "Montar"),
            ("umount /mnt", "Desmontar"),
            ("blkid", "UUIDs"),
            ("lsblk", "Bloques en árbol"),
            ("dd if=/dev/sda of=backup.img bs=4M", "Clonar disco"),
            ("smartctl -a /dev/sda", "Estado SMART"),
            ("fsck /dev/sda1", "Verificar FS"),
            ("sync", "Sincronizar buffers"),
            ("uname -a", "Info del kernel"),
            ("dmesg", "Mensajes del kernel"),
            ("free -h", "Memoria (legible)"),
            ("vmstat 1 10", "Estadísticas"),
        ],
        "Usuarios": [
            ("whoami", "Usuario actual"),
            ("id", "ID de usuario"),
            ("who", "Usuarios conectados"),
            ("last", "Últimos logins"),
            ("useradd usuario", "Crear usuario"),
            ("usermod -aG grupo usuario", "Agregar a grupo"),
            ("userdel -r usuario", "Eliminar usuario"),
            ("passwd usuario", "Cambiar contraseña"),
            ("groupadd grupo", "Crear grupo"),
            ("sudo cmd", "Ejecutar como root"),
            ("su - usuario", "Cambiar de usuario"),
            ("visudo", "Editar sudoers"),
        ],
        "Compresión": [
            ("tar -czf archivo.tar.gz dir", "Comprimir tar.gz"),
            ("tar -xzf archivo.tar.gz", "Extraer tar.gz"),
            ("tar -tf archivo.tar.gz", "Listar tar"),
            ("zip archivo.zip f1 f2", "Comprimir ZIP"),
            ("unzip archivo.zip", "Extraer ZIP"),
            ("gzip archivo", "Comprimir gzip"),
            ("gunzip archivo.gz", "Descomprimir gzip"),
        ],
        "Texto": [
            ("grep patrón archivo", "Buscar texto"),
            ("grep -r patrón /ruta", "Buscar recursivo"),
            ("sed 's/viejo/nuevo/g' archivo", "Reemplazar"),
            ("awk '{print \$1}' archivo", "Primera columna"),
            ("sort archivo", "Ordenar"),
            ("uniq -c archivo", "Contar únicos"),
            ("diff a b", "Diferencias"),
        ],
    },
    "Windows": {
        "Sistema": [
            ("systeminfo", "Información del sistema"),
            ("ipconfig", "Configuración IP"),
            ("ipconfig /all", "Configuración IP detallada"),
            ("ipconfig /flushdns", "Limpiar caché DNS"),
            ("ipconfig /release", "Liberar IP"),
            ("ipconfig /renew", "Renovar IP"),
            ("hostname", "Nombre del equipo"),
            ("whoami", "Usuario actual"),
            ("net user", "Listar usuarios"),
            ("net user usuario *", "Cambiar contraseña"),
            ("net localgroup", "Grupos locales"),
            ("net localgroup Administradores usuario /add", "Agregar admin"),
            ("net share", "Recursos compartidos"),
            ("net use Z: \\\\server\\share", "Mapear unidad"),
            ("net view", "Equipos en red"),
            ("netstat -an", "Puertos abiertos"),
            ("netstat -b", "Programas usando puertos"),
            ("netstat -r", "Tabla de rutas"),
            ("tasklist", "Listar procesos"),
            ("taskkill /F /PID 1234", "Matar proceso"),
            ("shutdown /r /t 0", "Reiniciar"),
            ("shutdown /s /t 0", "Apagar"),
            ("sfc /scannow", "Verificar archivos sistema"),
            ("chkdsk C: /f", "Verificar disco"),
            ("diskpart", "Particionar discos"),
            ("wmic cpu get name", "Info CPU"),
            ("wmic memorychip get capacity", "Info RAM"),
            ("wmic diskdrive get size", "Info disco"),
            ("msconfig", "Configuración sistema"),
            ("regedit", "Editor de registro"),
            ("gpedit.msc", "Políticas de grupo"),
            ("services.msc", "Servicios"),
            ("eventvwr.msc", "Visor de eventos"),
            ("compmgmt.msc", "Administración equipos"),
            ("devmgmt.msc", "Administrador dispositivos"),
            ("perfmon", "Monitor rendimiento"),
            ("resmon", "Monitor recursos"),
            ("dxdiag", "DirectX diagnostic"),
            ("mstsc", "Escritorio remoto"),
        ],
        "Red": [
            ("ping -n 4 8.8.8.8", "Ping"),
            ("ping -t 8.8.8.8", "Ping continuo"),
            ("tracert 8.8.8.8", "Traceroute"),
            ("pathping 8.8.8.8", "Ruta con análisis"),
            ("nslookup dominio.com", "DNS lookup"),
            ("nslookup dominio.com 8.8.8.8", "DNS con servidor"),
            ("nbtstat -n", "Nombre NetBIOS"),
            ("nbtstat -A 192.168.1.1", "Tabla NetBIOS remoto"),
            ("route print", "Tabla de enrutamiento"),
            ("route add 10.0.0.0 mask 255.0.0.0 192.168.1.1", "Agregar ruta"),
            ("arp -a", "Tabla ARP"),
            ("getmac", "Dirección MAC"),
            ("netsh interface show interface", "Interfaces"),
            ("netsh interface ip show config", "Config IP"),
            ("netsh wlan show profiles", "Perfiles WiFi"),
            ("netsh wlan show profile nombre key=clear", "Ver contraseña WiFi"),
            ("netsh wlan show networks", "Redes disponibles"),
            ("netsh advfirewall show allprofiles", "Firewall estado"),
            ("netsh advfirewall set allprofiles state off", "Desactivar firewall"),
            ("telnet 192.168.1.1 80", "Telnet a puerto"),
            ("ssh user@host", "SSH (OpenSSH)"),
            ("ftp host", "FTP"),
            ("bitsadmin", "Transferencia BITS"),
            ("winrm quickconfig", "Configurar WinRM"),
            ("winrm get winrm/config", "WinRM config"),
            ("test-netconnection 8.8.8.8 -port 443", "Test conexión (PS)"),
        ],
        "PowerShell": [
            ("Get-Process", "Listar procesos"),
            ("Get-Service", "Listar servicios"),
            ("Get-EventLog -LogName System -Newest 50", "Últimos logs"),
            ("Get-NetAdapter", "Adaptadores de red"),
            ("Get-NetIPAddress", "Direcciones IP"),
            ("Get-NetRoute", "Tabla de rutas"),
            ("Get-DnsClientCache", "Caché DNS"),
            ("Get-WmiObject Win32_ComputerSystem", "Info sistema"),
            ("Get-WmiObject Win32_BIOS", "Info BIOS"),
            ("Get-WmiObject Win32_LogicalDisk", "Discos lógicos"),
            ("Get-WmiObject Win32_NetworkAdapterConfiguration", "Config red"),
            ("Set-ExecutionPolicy RemoteSigned", "Política ejecución"),
            ("Invoke-Command -ComputerName server -ScriptBlock {cmd}", "Ejecución remota"),
            ("Enter-PSSession server", "Shell remoto"),
            ("New-Item -Path C:\\test -ItemType Directory", "Crear directorio"),
            ("Remove-Item C:\\test -Recurse", "Eliminar directorio"),
            ("Copy-Item C:\\orig C:\\dest -Recurse", "Copiar"),
            ("Move-Item C:\\orig C:\\dest", "Mover"),
            ("Get-Content C:\\archivo.txt", "Leer archivo"),
            ("Set-Content C:\\archivo.txt -Value \"texto\"", "Escribir archivo"),
            ("Select-String -Path C:\\*.txt -Pattern \"error\"", "Buscar en archivos"),
            ("Measure-Command { ping 8.8.8.8 }", "Medir tiempo comando"),
            ("Start-Transcript", "Iniciar log sesión"),
            ("Stop-Transcript", "Detener log sesión"),
        ],
    },
    "Docker": [
        ("docker ps", "Contenedores activos"),
        ("docker ps -a", "Todos los contenedores"),
        ("docker images", "Imágenes"),
        ("docker pull ubuntu:latest", "Descargar imagen"),
        ("docker run -it ubuntu bash", "Ejecutar interactivo"),
        ("docker run -d -p 80:80 nginx", "Ejecutar en bg"),
        ("docker start contenedor", "Iniciar contenedor"),
        ("docker stop contenedor", "Detener contenedor"),
        ("docker restart contenedor", "Reiniciar"),
        ("docker rm contenedor", "Eliminar contenedor"),
        ("docker rmi imagen", "Eliminar imagen"),
        ("docker exec -it contenedor bash", "Acceder a contenedor"),
        ("docker logs -f contenedor", "Seguir logs"),
        ("docker inspect contenedor", "Info detallada"),
        ("docker stats", "Estadísticas"),
        ("docker network ls", "Redes"),
        ("docker network create mired", "Crear red"),
        ("docker volume ls", "Volúmenes"),
        ("docker-compose up -d", "Levantar servicios"),
        ("docker-compose down", "Detener servicios"),
        ("docker system df", "Espacio usado"),
        ("docker system prune -a", "Limpiar todo"),
        ("docker build -t miapp .", "Construir imagen"),
        ("docker login", "Login registry"),
        ("docker push miapp:latest", "Subir imagen"),
        ("docker save -o miapp.tar miapp:latest", "Exportar a tar"),
        ("docker load -i miapp.tar", "Importar desde tar"),
    ],
    "Git": [
        ("git init", "Inicializar repo"),
        ("git clone url", "Clonar repo"),
        ("git add .", "Agregar todo"),
        ("git commit -m \"msg\"", "Crear commit"),
        ("git status", "Estado"),
        ("git log --oneline", "Historial resumido"),
        ("git diff", "Diferencias sin stage"),
        ("git branch", "Listar ramas"),
        ("git branch nombre", "Crear rama"),
        ("git checkout rama", "Cambiar rama"),
        ("git checkout -b nombre", "Crear y cambiar"),
        ("git merge rama", "Fusionar rama"),
        ("git pull", "Traer cambios"),
        ("git push", "Enviar cambios"),
        ("git remote -v", "Ver remotos"),
        ("git stash", "Guardar cambios temp"),
        ("git stash pop", "Recuperar stash"),
        ("git reset --hard HEAD", "Descartar cambios"),
        ("git tag v1.0", "Crear tag"),
        ("git show commit", "Mostrar commit"),
        ("git blame archivo", "Quién modificó"),
        ("git config --global user.name \"X\"", "Config nombre"),
        ("git config --global user.email \"x@y\"", "Config email"),
        ("git fetch", "Traer cambios sin merge"),
        ("git rebase rama", "Rebase"),
    ],
    "Kubernetes": [
        ("kubectl get nodes", "Nodos del cluster"),
        ("kubectl get pods", "Pods activos"),
        ("kubectl get pods -A", "Pods todos namespaces"),
        ("kubectl get services", "Servicios"),
        ("kubectl get deployments", "Deployments"),
        ("kubectl get namespaces", "Namespaces"),
        ("kubectl get configmaps", "ConfigMaps"),
        ("kubectl get secrets", "Secretos"),
        ("kubectl describe pod nombre", "Detalle pod"),
        ("kubectl logs pod", "Logs del pod"),
        ("kubectl logs -f pod", "Seguir logs"),
        ("kubectl exec -it pod -- bash", "Acceder a pod"),
        ("kubectl apply -f archivo.yaml", "Aplicar config"),
        ("kubectl delete pod nombre", "Eliminar pod"),
        ("kubectl scale deployment nombre --replicas=3", "Escalar"),
        ("kubectl port-forward pod 8080:80", "Forward puerto"),
        ("kubectl top nodes", "Recursos nodos"),
        ("kubectl top pods", "Recursos pods"),
        ("kubectl get events --sort-by='.lastTimestamp'", "Eventos"),
        ("kubectl config view", "Ver config"),
        ("kubectl config use-context nombre", "Cambiar contexto"),
        ("kubectl cluster-info", "Info cluster"),
        ("helm list", "Listar charts Helm"),
        ("helm install nombre chart", "Instalar chart"),
        ("helm upgrade nombre chart", "Actualizar chart"),
    ],
    "Bases de Datos": {
        "MySQL/MariaDB": [
            ("mysql -u root -p", "Conectar a MySQL"),
            ("SHOW DATABASES;", "Mostrar BD"),
            ("USE bd;", "Seleccionar BD"),
            ("SHOW TABLES;", "Mostrar tablas"),
            ("DESCRIBE tabla;", "Estructura tabla"),
            ("SELECT * FROM tabla;", "Consultar todo"),
            ("SELECT * FROM tabla WHERE id=1;", "Consultar con filtro"),
            ("INSERT INTO tabla VALUES (1, 'a');", "Insertar"),
            ("UPDATE tabla SET col='x' WHERE id=1;", "Actualizar"),
            ("DELETE FROM tabla WHERE id=1;", "Eliminar"),
            ("CREATE DATABASE bd;", "Crear BD"),
            ("CREATE TABLE t (id INT, nombre VARCHAR(50));", "Crear tabla"),
            ("ALTER TABLE t ADD COLUMN edad INT;", "Agregar columna"),
            ("DROP TABLE t;", "Eliminar tabla"),
            ("DROP DATABASE bd;", "Eliminar BD"),
            ("GRANT ALL ON bd.* TO user@localhost;", "Permisos"),
            ("FLUSH PRIVILEGES;", "Aplicar permisos"),
            ("mysqldump -u root -p bd > backup.sql", "Backup BD"),
            ("mysql -u root -p bd < backup.sql", "Restaurar BD"),
            ("SHOW PROCESSLIST;", "Procesos activos"),
            ("KILL id;", "Matar proceso"),
            ("EXPLAIN SELECT * FROM t;", "Plan ejecución"),
            ("CREATE INDEX idx_t ON t(col);", "Crear índice"),
        ],
        "PostgreSQL": [
            ("psql -U postgres", "Conectar PostgreSQL"),
            ("\\l", "Listar BD"),
            ("\\c bd", "Conectar a BD"),
            ("\\dt", "Listar tablas"),
            ("\\d tabla", "Describir tabla"),
            ("SELECT * FROM t;", "Consultar"),
            ("pg_dump bd > backup.sql", "Backup"),
            ("psql bd < backup.sql", "Restaurar"),
            ("CREATE DATABASE bd;", "Crear BD"),
            ("CREATE USER user WITH PASSWORD 'pass';", "Crear usuario"),
            ("GRANT ALL PRIVILEGES ON DATABASE bd TO user;", "Permisos"),
            ("\\du", "Listar usuarios"),
        ],
        "MongoDB": [
            ("mongosh", "Conectar MongoDB"),
            ("show dbs", "Mostrar BD"),
            ("use bd", "Usar BD"),
            ("show collections", "Colecciones"),
            ("db.coleccion.find()", "Buscar todo"),
            ("db.coleccion.find({campo: 'valor'})", "Buscar con filtro"),
            ("db.coleccion.insertOne({a: 1})", "Insertar uno"),
            ("db.coleccion.updateOne({a:1}, {\$set: {b:2}})", "Actualizar"),
            ("db.coleccion.deleteOne({a:1})", "Eliminar"),
            ("db.coleccion.countDocuments()", "Contar docs"),
            ("db.createCollection('col')", "Crear colección"),
            ("db.coleccion.createIndex({campo: 1})", "Crear índice"),
            ("mongodump --db bd --out backup/", "Backup"),
            ("mongorestore backup/", "Restaurar"),
            ("db.stats()", "Estadísticas"),
        ],
    },
    "Cloud": {
        "AWS CLI": [
            ("aws configure", "Configurar AWS CLI"),
            ("aws s3 ls", "Listar buckets"),
            ("aws s3 cp archivo s3://bucket/", "Subir archivo"),
            ("aws s3 sync dir s3://bucket/", "Sincronizar directorio"),
            ("aws ec2 describe-instances", "Listar instancias"),
            ("aws ec2 start-instances --instance-ids i-xxx", "Iniciar instancia"),
            ("aws ec2 stop-instances --instance-ids i-xxx", "Detener instancia"),
            ("aws ec2 describe-security-groups", "Grupos seguridad"),
            ("aws ec2 describe-vpcs", "Listar VPCs"),
            ("aws ec2 describe-subnets", "Listar subnets"),
            ("aws ec2 describe-volumes", "Listar volúmenes"),
            ("aws s3api list-buckets", "Buckets via API"),
            ("aws iam list-users", "Listar usuarios IAM"),
            ("aws iam list-roles", "Listar roles IAM"),
            ("aws lambda list-functions", "Listar funciones"),
            ("aws cloudformation describe-stacks", "Stacks CF"),
            ("aws sts get-caller-identity", "Identidad actual"),
            ("aws ecr list-repositories", "Repos ECR"),
        ],
        "Azure CLI": [
            ("az login", "Login Azure"),
            ("az account show", "Cuenta actual"),
            ("az vm list", "Listar VMs"),
            ("az vm start --name vm --resource-group rg", "Iniciar VM"),
            ("az vm stop --name vm --resource-group rg", "Detener VM"),
            ("az network vnet list", "Listar VNets"),
            ("az storage account list", "Storage accounts"),
            ("az storage container list", "Containers"),
            ("az group list", "Grupos recursos"),
            ("az aks list", "Clusters AKS"),
            ("az acr list", "Registries ACR"),
            ("az functionapp list", "Function Apps"),
            ("az sql server list", "SQL Servers"),
            ("az cosmosdb list", "CosmosDB"),
            ("az keyvault list", "Key Vaults"),
        ],
        "GCP CLI": [
            ("gcloud init", "Inicializar"),
            ("gcloud config list", "Config actual"),
            ("gcloud compute instances list", "Listar instancias"),
            ("gcloud compute instances start nombre", "Iniciar VM"),
            ("gcloud compute instances stop nombre", "Detener VM"),
            ("gcloud compute networks list", "Listar redes"),
            ("gcloud compute firewall-rules list", "Reglas firewall"),
            ("gcloud storage buckets list", "Buckets"),
            ("gcloud storage cp archivo gs://bucket/", "Copiar archivo"),
            ("gcloud kubernetes clusters list", "Clusters GKE"),
            ("gcloud sql instances list", "Cloud SQL"),
            ("gcloud iam service-accounts list", "Service accounts"),
        ],
    },
    "Virtualización": {
        "VMware": [
            ("esxcli vm process list", "VMs activas"),
            ("esxcli vm process kill --type=force --world-id=id", "Forzar apagado"),
            ("esxcli storage vmfs extent list", "Extents VMFS"),
            ("esxcli network nic list", "NICs físicas"),
            ("esxcli network ip interface list", "Interfaces IP"),
            ("esxcli network ip route list", "Rutas"),
            ("esxcli system version get", "Versión ESXi"),
            ("vim-cmd vmsvc/getallvms", "Todas las VMs"),
            ("vim-cmd vmsvc/power.on vmid", "Encender VM"),
            ("vim-cmd vmsvc/power.off vmid", "Apagar VM"),
            ("vim-cmd vmsvc/snapshot.create vmid nombre", "Snapshot VM"),
            ("vim-cmd vmsvc/snapshot.revert vmid", "Revertir snapshot"),
            ("vim-cmd hostsvc/hostsummary", "Resumen host"),
        ],
        "Proxmox": [
            ("qm list", "Listar VMs QEMU"),
            ("qm start vmid", "Iniciar VM"),
            ("qm stop vmid", "Detener VM"),
            ("qm shutdown vmid", "Apagado graceful"),
            ("qm reboot vmid", "Reiniciar VM"),
            ("qm create vmid --memory 2048 --net0 virtio,bridge=vmbr0", "Crear VM"),
            ("qm set vmid --ide2 local:iso/imagen.iso", "Montar ISO"),
            ("qm clone vmid newid", "Clonar VM"),
            ("qm migrate vmid target-node", "Migrar VM"),
            ("pct list", "Listar containers LXC"),
            ("pct start ctid", "Iniciar container"),
            ("pct stop ctid", "Detener container"),
            ("pct create ctid local:vztmpl/ubuntu.tar.gz", "Crear CT"),
            ("pct enter ctid", "Entrar al container"),
            ("pct resize ctid rootfs 10G", "Redimensionar"),
        ],
        "VirtualBox": [
            ("VBoxManage list vms", "Listar VMs"),
            ("VBoxManage list runningvms", "VMs activas"),
            ("VBoxManage startvm nombre --type headless", "Iniciar VM"),
            ("VBoxManage controlvm nombre poweroff", "Apagar VM"),
            ("VBoxManage controlvm nombre savestate", "Guardar estado"),
            ("VBoxManage snapshot nombre take snapshot-name", "Snapshot"),
            ("VBoxManage snapshot nombre restore snapshot-name", "Restaurar"),
            ("VBoxManage clonevm nombre --name clone-name", "Clonar"),
            ("VBoxManage import archivo.ova", "Importar OVA"),
            ("VBoxManage export nombre -o archivo.ova", "Exportar OVA"),
            ("VBoxManage modifyvm nombre --memory 4096", "Cambiar RAM"),
            ("VBoxManage modifyvm nombre --cpus 4", "Cambiar CPUs"),
            ("VBoxManage storagectl nombre --name SATA --add sata", "Agregar controlador"),
            ("VBoxManage storageattach nombre --storagectl SATA --port 0 --device 0 --type hdd --medium disco.vdi", "Agregar disco"),
        ],
    },
    "Python y Depuración": [
        ("python --version", "Versión de Python"),
        ("pip list", "Paquetes instalados"),
        ("pip install paquete", "Instalar paquete"),
        ("pip uninstall paquete", "Desinstalar"),
        ("pip freeze > requirements.txt", "Exportar dependencias"),
        ("pip install -r requirements.txt", "Instalar desde req"),
        ("python -m venv venv", "Crear entorno virtual"),
        ("source venv/bin/activate", "Activar venv (Linux)"),
        ("venv\\Scripts\\activate", "Activar venv (Windows)"),
        ("deactivate", "Desactivar venv"),
        ("python -m http.server 8000", "Servidor HTTP simple"),
        ("python -c \"print('hello')\"", "Ejecutar código inline"),
        ("python script.py", "Ejecutar script"),
        ("python -m pdb script.py", "Depurar con pdb"),
        ("pdb.set_trace()", "Breakpoint en código"),
        ("python -m cProfile script.py", "Perfilado"),
        ("python -m pytest tests/", "Ejecutar tests"),
        ("pylint script.py", "Análisis estático"),
        ("black script.py", "Formatear código"),
        ("mypy script.py", "Type checking"),
        ("flake8 script.py", "Linting"),
        ("ipython", "Python interactivo mejorado"),
        ("jupyter notebook", "Jupyter Notebook"),
        ("jupyter lab", "Jupyter Lab"),
    ],
    "Monitorización": [
        ("promtool check rules reglas.yml", "Validar reglas Prometheus"),
        ("promtool check config prometheus.yml", "Validar config Prometheus"),
        ("curl http://localhost:9090/api/v1/query?query=up", "Query Prometheus API"),
        ("node_exporter", "Node exporter metrics"),
        ("blackbox_exporter", "Blackbox exporter"),
        ("grafana-cli plugins list-remote", "Plugins Grafana"),
        ("grafana-cli admin reset-admin-password newpass", "Reset pass Grafana"),
        ("curl http://localhost:3001/api/health", "Health check Grafana"),
        ("telegraf --config /etc/telegraf/telegraf.conf", "Test config Telegraf"),
        ("telegraf --test --input-filter cpu", "Test input Telegraf"),
        ("influx -host localhost -port 8086", "Conectar InfluxDB CLI"),
        ("influx -execute 'SHOW DATABASES'", "Mostrar BD InfluxDB"),
        ("elasticsearch -Ecluster.name=mycluster", "Iniciar ES"),
        ("curl localhost:9200/_cluster/health", "Health ES"),
        ("curl localhost:9200/_cat/indices?v", "Índices ES"),
        ("/usr/share/logstash/bin/logstash -f config.conf", "Ejecutar Logstash"),
        ("kibana", "Iniciar Kibana"),
        ("nagios -v config.cfg", "Verificar config Nagios"),
        ("check_nrpe -H host -c check_load", "Check NRPE"),
        ("zabbix_get -s host -k item.key", "Obtener item Zabbix"),
        ("zabbix_sender -z server -s host -k key -o value", "Enviar dato Zabbix"),
        ("zabbix_sender -z server -s host -k key -o value -p 10051", "Enviar dato Zabbix (puerto específico)"),
        ("zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf", "Iniciar agente Zabbix"),
        ("zabbix_agentd -t key", "Probar item del agente"),
        ("zabbix_server -c /etc/zabbix/zabbix_server.conf", "Iniciar servidor Zabbix"),
        ("curl -X POST http://localhost:8080/api_jsonrpc.php -d '{\"jsonrpc\":\"2.0\",\"method\":\"apiinfo.version\",\"params\":{},\"id\":1}' -H 'Content-Type: application/json'", "API Zabbix - ver versión"),
        ("curl -X POST http://localhost:8080/api_jsonrpc.php -d '{\"jsonrpc\":\"2.0\",\"method\":\"user.login\",\"params\":{\"username\":\"Admin\",\"password\":\"zabbix\"},\"id\":2}' -H 'Content-Type: application/json'", "API Zabbix - login"),
        ("curl -X POST http://localhost:8080/api_jsonrpc.php -d '{\"jsonrpc\":\"2.0\",\"method\":\"host.get\",\"params\":{\"output\":\"extend\"},\"auth\":\"TOKEN\",\"id\":3}' -H 'Content-Type: application/json'", "API Zabbix - listar hosts"),
        ("curl -X POST http://localhost:8080/api_jsonrpc.php -d '{\"jsonrpc\":\"2.0\",\"method\":\"problem.get\",\"params\":{\"recent\":\"true\",\"limit\":\"10\"},\"auth\":\"TOKEN\",\"id\":4}' -H 'Content-Type: application/json'", "API Zabbix - problemas activos"),
        ("curl -X POST http://localhost:8080/api_jsonrpc.php -d '{\"jsonrpc\":\"2.0\",\"method\":\"trigger.get\",\"params\":{\"output\":\"extend\",\"filter\":{\"value\":\"1\"}},\"auth\":\"TOKEN\",\"id\":5}' -H 'Content-Type: application/json'", "API Zabbix - triggers activos"),
        ("curl -X POST http://localhost:8080/api_jsonrpc.php -d '{\"jsonrpc\":\"2.0\",\"method\":\"host.create\",\"params\":{\"host\":\"UPS-192_168_1_50\",\"name\":\"UPS Oficina\",\"interfaces\":[{\"type\":1,\"main\":1,\"useip\":1,\"ip\":\"192.168.1.50\",\"dns\":\"\",\"port\":\"10050\"}],\"groups\":[{\"groupid\":\"2\"}],\"templates\":[{\"templateid\":\"10001\"}]},\"auth\":\"TOKEN\",\"id\":6}' -H 'Content-Type: application/json'", "API Zabbix - crear host UPS"),
        ("snmpwalk -v2c -c public host 1.3.6.1.2.1.33", "SNMP walk UPS-MIB para Zabbix"),
        ("snmptrap -v2c -c public localhost '' 1.3.6.1.4.1.318 UPS-MIB::upsTrapOnBattery", "Enviar trap SNMP UPS a Zabbix"),
    ],
}


def list_categories():
    return list(CONSOLE_COMMANDS.keys())

def get_commands(os_type):
    return CONSOLE_COMMANDS.get(os_type, {})

def search_commands(query):
    results = {}
    for category, subcategories in CONSOLE_COMMANDS.items():
        if isinstance(subcategories, dict):
            for subcat, cmds in subcategories.items():
                for cmd, desc in cmds:
                    if query.lower() in cmd.lower() or query.lower() in desc.lower():
                        if category not in results:
                            results[category] = {}
                        if subcat not in results[category]:
                            results[category][subcat] = []
                        results[category][subcat].append((cmd, desc))
        elif isinstance(subcategories, list):
            for cmd, desc in subcategories:
                if query.lower() in cmd.lower() or query.lower() in desc.lower():
                    if category not in results:
                        results[category] = []
                    results[category].append((cmd, desc))
    return results
